### PR TITLE
Fix process list copy/save appending `(null)` on MySQL

### LINKED ISSUE #2322: Copy query from processlist has (NULL) at end
- Sequel Ace Version (including build number): 5.10 (Build 20096)
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 15.3.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.mysql_aurora.3.08.2 (**AWS RDS Auroa**)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Coping a process from the processlist has ` (null)` at the end of the query.

**Steps To Reproduce**
1. Connect to MySQL host
1. Open processlist (CMD + Option + p)
1. Copy a query
2. See end of the query (it has ` (null)`)

Image

```sql
311615 root 127.0.0.1:36684 <null> Query 0 init SHOW FULL PROCESSLIST (null)
```

**Expected Behaviour**
Without the ` (null)`
```sql
311615 root 127.0.0.1:36684 <null> Query 0 init SHOW FULL PROCESSLIST
```

**Related Issues**
Part of (#2153) and PR (#2155)

### PR DESCRIPTION
**Pull request by Jason-Morcos**
## Summary
Fixes a long-standing process-list export issue where copied/saved rows could include literal `(null)` text in output.

This PR now:
- moves process-row serialization into a shared Swift extension on `SPProcessListController`
- uses typed key handling for process columns to reduce brittle string formatting logic
- reuses the same serializer for both **Copy** and **Save As** paths
- only includes `Progress` when connected to MariaDB
- normalizes `nil`/`NSNull` values to empty strings instead of emitting `(null)`

## Root Cause
Both Copy and Save paths built rows independently with `stringWithFormat` and direct dictionary lookups. For missing/null values this produced unintended `(null)` output, and the duplicated logic drifted over time.

## Implementation Details
- Added a Swift serializer helper in `Source/Other/Extensions/NSDictionaryExtension.swift`:
  - `SPProcessListController.serializedProcessRow(_:includeProgress:)`
- Introduced typed process-list keys in Swift (`ProcessListColumnKey`) to keep serialization safer and easier to maintain.
- Updated ObjC call sites in `Source/Controllers/SubviewControllers/SPProcessListController.m` to use the shared serializer.

## User Impact
- Copying or saving process lists no longer appends `(null)` for missing fields.
- Output is consistent between clipboard and saved-file flows.

## Testing
- `xcodebuild test -project sequel-ace.xcodeproj -scheme "Unit Tests" -destination "platform=macOS" -only-testing:'Unit Tests/SPDatabaseActionTest'`
- Verified manually that serializer behavior omits `Progress` for MySQL and conditionally includes it for MariaDB when present.

Closes #2322

## Summary by CodeRabbit

* **Refactor**
  * Improved internal code organization for process data handling.

* **Tests**
  * Added unit tests for process row serialization functionality.

### CODE REVIEW

File: Source/Controllers/SubviewControllers/SPProcessListController.m [hunk 1]
```diff
@@ -455,6 +438,33 @@ - (void)windowWillClose:(NSNotification *)notification
 #pragma mark -
 #pragma mark Private API
 
++ (NSString *)_serializedProcessRow:(NSDictionary *)process includeProgress:(BOOL)includeProgress
```
Comment (Kaspik) [inline Source/Controllers/SubviewControllers/SPProcessListController.m]: Can we move this to Swift (extension of this file) and make it type safe?
