### PR TITLE
#fixed Users screen schemas not updating

### LINKED ISSUE #723: Account creation: Schema privileges does not display last added schema
This must be one of the latest updates that caused it as I cannot now find the last added schema when adding new user account. Steps to reproduce:

1. Add new database
2. Click Users button in the toolbar, add new Account and navigate to Schema Privileges
3. The last added database is not listed under Schemas

The only way for me to be able to attach privileges to the new database is by re-connecting and going through the user account again.

### PR DESCRIPTION
**Pull request by jamesstout**
## Changes:
- Post notifications when a database is created/renamed/dropped 
- Listen for `SPDatabaseCreatedRemovedRenamedNotification` and reload the schema list when notified

## Closes following issues:
- Closes #723  

## Tested:
- Processors:
  - [x] Intel
  - [ ] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [x] 10.15.x (Catalina)
  - [ ] 11.x (Big Sur)
- Xcode Version: 12.4 (12D4e)
- Localizations:
  - [ ] English
  - [ ] Spanish
  - [ ] Other (please specify)

### CODE REVIEW

File: Source/Controllers/MainViewControllers/SPDatabaseDocument.m [hunk 1]
```diff
@@ -111,6 +111,7 @@ @interface SPDatabaseDocument ()
 @property (nonatomic, strong) NSImage *textAndCommandMacwindowImage API_AVAILABLE(macos(11.0));
 @property (nonatomic, strong, readwrite) SPWindowController *parentWindowController;
 @property (assign) BOOL appIsTerminating;
+@property (nonatomic, strong) NSNotificationCenter *defaultNotificationCenter;
```
Comment (Kaspik) [inline Source/Controllers/MainViewControllers/SPDatabaseDocument.m:114]: Dealloc is not called so holding it is even worse right now... Not sure if we should do this 😭

Comment (jamesstout) [reply Source/Controllers/MainViewControllers/SPDatabaseDocument.m:114]: OK, I just hate seeing 16 `[NSNotificationCenter defaultCenter] `calls...

Comment (jamesstout) [reply Source/Controllers/MainViewControllers/SPDatabaseDocument.m]: reverted.

**Review by Jason-Morcos — APPROVED** [review]
