### PR TITLE
Fixed #477 and #504. Adjusted formatters with more extensions, so we won't update the static version with styling

### LINKED ISSUE #477: TABLE INFORMATION panel size issues and header label strangeness
- Sequel Ace Version: 2.2.2
- macOS Version: 10.15.7
- MySQL Version: 5.5.37

**Description**
The Table/View information panel shown in the bottom left below the list of tables and views has a couple of issues. May not be top priority, by next time you're looking at the UI, here's some feedback:
- The panel now seems to have fixed proportional height when open (instead of fixed absolute like in Sequel Pro), which means it's usually too big, and it can't be resized as expected. 
- The gray header "TABLE INFORMATION" looks like a static label, but if you click it it turns out you can select it (unclear why, and unlike the same style header "TABLES & VIEWS" at the top)
- If you then click the header it turns out it's now a sort of toggle button as well, toggling the panel to an empty ACTIVITIES state, while also in a sort of buggy way toggling the selection state of the row, leaving the background and text blue/gray/white in cycles.
- If you close the panel using the button at the bottom an empty gap appears above the Filter field at the top of the column.

**Steps To Reproduce**
1. Try resizing the window or Table information panel, click table information header.

**Expected Behaviour**
Have table information panel either be fixed appropriate size or possible to resize. Expect the header to be static inert, with nothing happening if you click it. 

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, all issues present in latest beta.

### LINKED ISSUE #504: Row count shown as Kib
- Sequel Ace Version: 2.3.0
- macOS Version: 10.15.7
- MySQL Version: 5.7.32

**Description**
Row count and row selected number are treated as byte count

**Steps To Reproduce**
1. select a table on left
2. look at numbers on bottom

**Expected Behaviour**
Numbers should be displayed as number without unit of measure

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No beta ATM

Schermata 2020-11-16 alle 22 51 33

### PR DESCRIPTION
**Pull request by SumBeam**
What does this implement/fix? Explain your changes.
---------------------------------------------------
`[NSNumberFormatter setFormat...]` was updating the format for all the NSNumberFormatter in the project, in the issue #504 you'll see everywhere the KiB format. I introduced a small change in the extension to have a little bit more flexibility + less copy-paste

Does this close any currently open issues?
------------------------------------------
Yes -> #504 

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**macOS Version:** 10.15.4

**Sequel-Ace Version:** main-3_0_0

### CODE REVIEW

**Review by Jason-Morcos — COMMENTED** [review]
I like the thought, but will need to check in with @jamesstout. I think the issue was likely introduced by https://github.com/Sequel-Ace/Sequel-Ace/pull/451. It sounded like the formatters were intentionally made static for performance reasons

**Comment by jamesstout** [comment]
I thought I'd caught all formats but must have missed stringForByteSize.

This is good, it's still static, but flexible. Nice catch.

File: Source/Other/Extensions/NumberFormatterExtension.swift [hunk 1]
```diff
@@ -9,11 +9,18 @@
 import Foundation
 
 extension NumberFormatter {
+	@objc static let decimalStyleFormatter = decimal()
 
-	@objc public static var decimalStyleFormatter: NumberFormatter = {
-			
+	@objc static func decimal() -> NumberFormatter {
```
Comment (Kaspik) [inline Source/Other/Extensions/NumberFormatterExtension.swift:14]: Why this change though? the `decimal()` is not used anywhere except above, and the new method below doesn't use it... so why not just adding the new one?

Comment (SumBeam) [reply Source/Other/Extensions/NumberFormatterExtension.swift:14]: Oh, yes you are right. I'll update it, I was testing out some stuff, reverted it but I forgot to revert this part

File: Source/Other/Extensions/NumberFormatterExtension.swift [hunk 2]
```diff
@@ -9,11 +9,16 @@
...
 
 extension NumberFormatter {
-
 	@objc public static var decimalStyleFormatter: NumberFormatter = {
-			
 		let formatter = NumberFormatter()
 		formatter.numberStyle = .decimal
 		return formatter
-	}()
+	}
```
Comment (Kaspik) [inline Source/Other/Extensions/NumberFormatterExtension.swift:16]: missing `()`

File: Source/Other/Extensions/NumberFormatterExtension.swift [hunk 3]
```diff
@@ -9,11 +9,16 @@
...
+
+	@objc static func withFormat(_ format: String) -> NumberFormatter {
```
Comment (Kaspik) [inline Source/Other/Extensions/NumberFormatterExtension.swift:18]: can we make this init instead of `withFormat(_ format:) func`? Swift doesn't really use `with` as it's automated, so `@objc init(format: String)` is for objective C translated as `initWithFormat:`

Comment (Kaspik) [reply Source/Other/Extensions/NumberFormatterExtension.swift:18]: Or just somehow rename it so it's clear it creates new formatter into memory...

File: Source/Other/Extensions/NumberFormatterExtension.swift (hunk 2 above)
Comment (SumBeam) [reply Source/Other/Extensions/NumberFormatterExtension.swift]: Fixed

File: Source/Other/Extensions/NumberFormatterExtension.swift [hunk 4]
```diff
@@ -9,11 +9,16 @@
...
 extension NumberFormatter {
-
 	@objc public static var decimalStyleFormatter: NumberFormatter = {
-			
 		let formatter = NumberFormatter()
 		formatter.numberStyle = .decimal
 		return formatter
 	}()
+
+	@objc public static func formatter(_ format: String) -> NumberFormatter {
```
Comment (Kaspik) [inline Source/Other/Extensions/NumberFormatterExtension.swift:18]: I know I'm annoying (sorry!) but `formatter(format:` would be better so it's `formatterWithFormat` in Objective-C... for newcomers and more junior developers this wouldn't say anything what the parameter means :)

Comment (SumBeam) [reply Source/Other/Extensions/NumberFormatterExtension.swift]: Fixed. And no problem! Happy to receive feedback on the changes :)

**Review by Kaspik — APPROVED** [review]
