### PR TITLE
#fixed saving individual query history

### LINKED ISSUE #913: Query history can't be display complete in one row
- Sequel Ace Version (including build number): 3.2.1 build 3020
- Sequel Ace Source (App Store/GitHub/Homebrew): APP Store
- macOS Version:11.2.2
- Processor Type (Intel/Apple): intel
- MySQL Version: any
- macOS Localization: EN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes. The problem was keep shown in the version 3.2.2(build 3021)
 

**Description**
Query history was split to many parts if the statement contain new line character.
For ex: select *from 
(there was new line) table1 where a = 1;
After run this statement there are 2 lines shown on the "Query History";

**Steps To Reproduce**
1. Open the app and connect to any MySQL server
2.run any sql statement with new line character(may be:\r\n). complex statement will be better
3.Click Query History
4.You will see the statement may has been split to many row
5.Click any row of the Query History you will see a part of the statement will fill into query windows but not the complete statement.

**Expected Behaviour**
The executed statement should be fill into query window completely after click Query History.

**Related Issues**
---

**Additional Context**
WeCom20210226-170848@2x

### PR DESCRIPTION
**Pull request by jamesstout**
## Changes:
- save individually now splits on `;`

## Closes following issues:
- Closes #913 

## Tested:
- Processors:
  - [x] Intel
  - [ ] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [x] 11.x (Big Sur)
- Xcode Version: 12.4 (12D4e)
- Localizations:
  - [ ] English
  - [ ] Spanish
  - [ ] Other (please specify)

### CODE REVIEW

File: UnitTests/SPStringAdditionsTests.m [hunk 1]
```diff
@@ -635,6 +635,18 @@ - (void)testSeparatedIntoLines{
 
 }
 
+- (void)testSeparatedIntoLinesByCharsetObjC{
+
+    NSString *str = @"SELECT * FROM `HKWarningsLog`\n LIMIT 1000;\nSELECT * FROM `HKWarningsLog`\n LIMIT 1000;\nSELECT * FROM `HKWarningsLog` LIMIT 1000\n;";
+    NSArray *expectedArray = @[@"SELECT * FROM `HKWarningsLog`\n LIMIT 1000",@"\nSELECT * FROM `HKWarningsLog`\n LIMIT 1000", @"\nSELECT * FROM `HKWarningsLog` LIMIT 1000\n"];
```
Comment (Jason-Morcos) [inline UnitTests/SPStringAdditionsTests.m:641]: Maybe we should trim leading/trailing white space and new lines from the specific query?

**Review by Jason-Morcos — APPROVED** [review]

File: UnitTests/SPStringAdditionsTests.m (hunk 1 above)
Comment (Jason-Morcos) [reply UnitTests/SPStringAdditionsTests.m:641]: Gonna go ahead and merge anyways cause it fixes the bug indeed, just a thought here
