### PR TITLE
Fixed #368 Added Clear Text Plugin checkbox to the connection overvie…

### LINKED ISSUE #368: LDAP Error:  Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled
- Sequel Ace Version:  2.1.8
- macOS Version: 10.15.6
- MySQL Version: 8.0.1

**Description**
Connecting to our MySQL 8 DB using LDAP.  Keep getting this error "MySQL said: Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled", when connecting with our LDAP account.  When we connect using the root account, it works fine.  We do not see this issue with other tools we use in our company.  

We have tried the latest Beta version as well and we are still seeing the same issue.  In my profile. I have set:

`export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=y`

How can we get this tool to work with LDAP so our engineers can use this.  They prefer to use this tool over the other ones.

### PR DESCRIPTION
**Pull request by SumBeam**
What does this implement/fix? Explain your changes.
---------------------------------------------------
It's adding a checkbox to the connection screen which enabled the cleartext plugin option on the mysqlconnection lib for this current connection.

Does this close any currently open issues?
------------------------------------------
Yes. #368 

Any relevant logs, error output, etc?
-------------------------------------
Screenshot of how it looks:

Any other comments?
-------------------
It's my first PR to a Mac app, please let me know if I missed something.

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**macOS Version:** 10.15.4

**Sequel-Ace Version:** …

### CODE REVIEW

File: Frameworks/SPMySQLFramework/Source/SPMySQLConnection.h [hunk 1]
```diff
@@ -46,8 +46,11 @@
...
     
-    //Special connection settings
-    BOOL allowDataLocalInfile;
+  //Special connection settings
+  BOOL allowDataLocalInfile;
+    
+  // Clear text plugin
+  BOOL enableClearTextPlugin;
 
 	// SSL connection details
```
Comment (Jason-Morcos) [inline Frameworks/SPMySQLFramework/Source/SPMySQLConnection.h:55]: Spacing might have got a little funky here?

**Review by Jason-Morcos — COMMENTED** [review]
Looks good to me code-wise, but likely-unrelated DYLIB issues are preventing me from building locally to test. Will let other take a look too.

We may want to have a broader conversation about that connection view UI that's getting increasingly messy - perhaps we could have some sort of modal-style view to edit these kinds of connection settings (allow local data infile and cleartext) instead of adding more and more options. Food for thought.

File: Frameworks/SPMySQLFramework/Source/SPMySQLConnection.h (hunk 1 above)
Comment (SumBeam) [reply Frameworks/SPMySQLFramework/Source/SPMySQLConnection.h:55]: Yeah.. I'll update that. I think my editor was not setup correctly with tabs/spaces

**Comment by SumBeam** [comment]
> Looks good to me code-wise, but likely-unrelated DYLIB issues are preventing me from building locally to test. Will let other take a look too.
> 
> We may want to have a broader conversation about that connection view UI that's getting increasingly messy - perhaps we could have some sort of modal-style view to edit these kinds of connection settings (allow local data infile and cleartext) instead of adding more and more options. Food for thought.

I agree. We shouldn't bother the normal user with those advanced settings. I like the view of MySQL Workbench, it's clean with the necessary params for just the connection, but if you need the advanced options they are really easy to find.

File: Frameworks/SPMySQLFramework/Source/SPMySQLConnection.h (hunk 1 above)
Comment (SumBeam) [reply Frameworks/SPMySQLFramework/Source/SPMySQLConnection.h]: Fixed, looks like the allowDataLocalInFile was added with spaces instead of tabs.. I replaced it with tabs in a new commit so its consistent with the file.

**Review by jamesstout — COMMENTED** [review]
> Will let other take a look too.

Looks good to me.

**Review by Kaspik — APPROVED** [review]
Ohh god I would love to cleanup the connections view and change the behavior completely... though I took a look and to perfect flow I want to build it's days of work. 😞

**Comment by Jason-Morcos** [comment]
@SumBeam @Kaspik I believe this PR unfortunately broke creating new connections in Sequel Ace
Screen Shot 2020-11-25 at 12 47 45
