### PR TITLE
Fix repeated modal loop for failing view metadata/status loads

### LINKED ISSUE #2299: Unable to get database character set encodings when connecting to ShardingSphere-Proxy
When connecting Sequel Ace to a MySQL-compatible proxy service such as ShardingSphere-Proxy, 
the connection fails with the error:

"Unable to get database character set encodings"

This seems to happen because Sequel Ace runs `SHOW VARIABLES LIKE 'character_set_%'` and/or `SHOW COLLATION`
on connect, but the proxy may not implement these commands fully or returns a reduced result set.

This makes Sequel Ace unusable for MySQL protocol-compatible proxies, even when the actual SQL queries work fine.

### LINKED ISSUE #2313: catch22: message for non-granted view in loop, because don't leave view before next message
- Sequel Ace Version (including build number): 5.0.9 build 20095
- Sequel Ace Source (App Store/GitHub/Homebrew): apple dmg
- macOS Version: 26.1 Tahoe
- Processor Type (Intel/Apple): Apple M2
- MySQL Version: 8.0.40 for macos14 on arm64 (MySQL Community Server - GPL)
- macOS Localization: italian it_IT

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
It's a catch22 UI.
Hi, i made user w/password, then GRANT ALL it (in dev) then loaded 
a previuos dump w/tables and views. When i choose a view i give 
an error message, but i need to kill the client with ctrl-option-esc
because i can't change selection in Sequel Ace. I can't do in time
between closing modal message than re-appears.
Consider almost a 2 second timeout or stop the message after 3 times.

Si è verificato un errore durante il recupero delle informazioni.
MySQL ha detto: View 'pcpdb.pcp_contest_juries_view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

**Steps To Reproduce**
1. create user w/password
2. Load in mysql a table data and view
3. try to access table data (ok) tabel view (ko: message then loop message)

**Expected Behaviour**
Give us almost 2 sec to change selection to avoid message.

**Related Issues**
None

**Additional Context**
None

Image

### PR DESCRIPTION
**Pull request by Jason-Morcos**
## Summary
This PR now fully addresses two bugs:
- The repeated modal error loop when view/table metadata or status loading fails (#2313).
- Connection failures where charset metadata cannot be fetched from MySQL-compatible proxies (#2299).

## What changed
- Added failure-state tracking in `SPTableData` for table/view metadata and status loads to prevent repeated retry/alert loops for the same failing selection.
- Added guard checks so repeated internal reload paths skip known-failing metadata/status loads until cache reset or a successful load occurs.
- Added charset metadata fallback logic in `SPDatabaseData`:
  - first try `information_schema.character_sets`
  - then fallback to `SHOW CHARACTER SET`
  - then fallback to a minimal UTF-8-compatible list (`utf8mb4`, `utf8`, `latin1`)
- Added row normalization so `SHOW CHARACTER SET` and `information_schema` results are mapped to consistent keys (`CHARACTER_SET_NAME`, `DESCRIPTION`, `DEFAULT_COLLATE_NAME`, `MAXLEN`).
- Added a one-time warning when Sequel Ace must use fallback charset metadata.

## Tests
- Added focused unit tests for charset normalization/fallback behavior:
  - `SPDatabaseDataCharsetTests` in `UnitTests/SPDatabaseActionTest.m`
- Verified with:
  - `xcodebuild test -project sequel-ace.xcodeproj -scheme "Unit Tests" -configuration Debug -destination 'platform=macOS' -only-testing:"Unit Tests/SPDatabaseDataCharsetTests" -only-testing:"Unit Tests/SPFunctionsTests/testIsEmpty"`

## Behavioral impact
- For #2313, users still see the first relevant metadata/status error, but repeated internal reload attempts no longer trap the UI in an alert loop.
- For #2299, connections no longer fail solely because charset metadata queries are unsupported or reduced by proxies; Sequel Ace continues with a safe fallback list and informs the user.

Closes #2313
Closes #2299

## Follow-up Refinement
- Refactored newly added normalization/load-failure matching logic into Swift helper types (`SPCharacterSetMetadataNormalizer`, `SPTableLoadFailure`) to improve type safety while preserving existing Objective-C call sites.

### CODE REVIEW

File: Source/Controllers/DataControllers/SPDatabaseData.m [hunk 1]
```diff
@@ -415,6 +444,64 @@ - (NSArray *)_getDatabaseDataForQuery:(NSString *)query
 	return [result getAllRows];
 }
 
+- (NSArray *)_normalizedCharacterSetEncodingsFromRows:(NSArray *)rows
```
Comment (Kaspik) [inline Source/Controllers/DataControllers/SPDatabaseData.m:447]: Again, would love to see this in Swift, typesafe

File: Source/Controllers/DataControllers/SPTableData.m [hunk 2]
```diff
@@ -87,6 +104,62 @@ - (void)documentWillClose:(NSNotification *)notification {
     }
 }
 
+- (BOOL)_shouldSkipTableInformationLoadForTable:(NSString *)tableName database:(NSString *)database tableType:(SPTableType)tableType
```
Comment (Kaspik) [inline Source/Controllers/DataControllers/SPTableData.m:100]: ^^
