### PR TITLE
fix-alias-completions #fixed

### LINKED ISSUE #633: The problem of code completion
- Sequel Ace Version:  3.0.0 3006
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.12

**Description**
  In the case of a query table with an alias, the fields in my code completion prompt would be for the entire database, not the query table
**Steps To Reproduce**
1. I have two tables in db of test.eg: student and teacher
2.I make a query operation ,like this:
`select * from teacher t where t.name='sd'`
and the alias name 't' and I type '.' the the prompt like ：
image

### PR DESCRIPTION
**Pull request by jamesstout**
## Changes:
The code to search for aliases when performing completion, was not using the correct query range. This fixes that.

## Closes following issues:
Closes #633

## Tested:
- Processors:
  - [x] Intel
  - [ ] Apple Silicon
- macOS versions:
  - [ ] 10.12
  - [ ] 10.13
  - [ ] 10.14
  - [ ] 10.15
  - [x] 11.0
- Xcode version: 12.2 (12B45b)

### CODE REVIEW

File: Source/Views/TextViews/SPTextView.m [hunk 1]
```diff
@@ -836,7 +836,7 @@ - (void)doCompletionByUsingSpellChecker:(BOOL)isDictMode fuzzyMode:(BOOL)fuzzySe
 			NSArray *allTables = [[dbs objectForKey:conID] allKeys];
 			// Check if found table name is known, if not parse for aliases
 			if(![allTables containsObject:[NSString stringWithFormat:@"%@%@%@", conID, SPUniqueSchemaDelimiter, tableName]]) {
-				NSString *currentQuery = [[self string] substringWithRange:[customQueryInstance currentQueryRange]];
+                NSString *currentQuery = [[self string] substringWithRange:NSMakeRange(0, self.string.length)];
```
Comment (Kaspik) [inline Source/Views/TextViews/SPTextView.m:839]: `self.string substringWithRange:Range of whole string` - why don't we take the string itself? 😄

**Review by Kaspik — APPROVED** [review]

**Comment by evil-sandeep** [comment]
in my vs code when click '-' sign it automatic show me -e]633;Completions;0;1;1; this command
