### PR TITLE
Crashfix: import

### LINKED ISSUE #55: Crash after import
- Sequel Ace Version: 2.0.1 Build 2029
- macOS Version: 10.15.5
- MySQL Version: 5.7.29

**Description**
Performed a database import of .sql file from keyboard shortcut Cmd+Shift+I (not sure if relevant, but just in case).

**Steps To Reproduce**
1. Press Cmd+Shift+I to start import dialog
2. Select SQL file
3. Observe crash
4. Receive notification of successful data import

**Expected Behaviour**
SQL import finishes and does not crash application

**Additional Context**
<details><summary>Crash Log</summary>
Process:               Sequel Ace [47813]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
Identifier:            com.sequel-ace.sequel-ace
Version:               2.0.1 (2029)
App Item ID:           1518036000
App External ID:       836441131
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Ace [47813]
User ID:               1639081008

Date/Time:             2020-06-22 10:16:33.358 -0400
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        C4DD4902-ED07-F56D-FA3A-7A2922CE5F59

Sleep/Wake UUID:       6392E86E-EABD-4CAE-BC16-29CAF8DCD1D4

Time Awake Since Boot: 530000 seconds
Time Since Wake:       7800 seconds

System Integrity Protection: enabled

Crashed Thread:        9  SPDataImport background import task (SPDatabaseDocument#1)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007c2c4328ddf0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [47813]

VM Regions Near 0x7c2c4328ddf0:
    Stack                  0000700007b13000-0000700007b95000 [  520K] rw-/rwx SM=COW  thread 7
--> 
    MALLOC_TINY            00007feac0c00000-00007feac0d00000 [ 1024K] rw-/rwx SM=PRV  

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6e2eadfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6e2eb170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff34347f85 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff34346a52 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff34345ece CFRunLoopRunSpecific + 462
5   com.apple.HIToolbox           	0x00007fff32f74abd RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff32f747d5 ReceiveNextEventCommon + 584
7   com.apple.HIToolbox           	0x00007fff32f74579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff315bc829 _DPSNextEvent + 883
9   com.apple.AppKit              	0x00007fff315bb070 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  com.apple.AppKit              	0x00007fff315acd7e -[NSApplication run] + 658
11  com.apple.AppKit              	0x00007fff3157eb86 NSApplicationMain + 777
12  libdyld.dylib                 	0x00007fff6e1a9cc9 start + 1

Thread 1:: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib        	0x00007fff6e2ed882 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6e3ae425 _pthread_cond_wait + 698
2   libc++.1.dylib                	0x00007fff6b47d592 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   com.apple.JavaScriptCore      	0x00007fff38b42224 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 84
4   com.apple.JavaScriptCore      	0x00007fff38b46a2b bmalloc::Scavenger::threadRunLoop() + 299
5   com.apple.JavaScriptCore      	0x00007fff38b465f9 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9
6   com.apple.JavaScriptCore      	0x00007fff38b48cd7 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 39
7   libsystem_pthread.dylib       	0x00007fff6e3ae109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6e3a9b8b thread_start + 15

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6e2eadfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6e2eb170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff34347f85 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff34346a52 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff34345ece CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff3175e144 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6e3ae109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6e3a9b8b thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6e3a9b68 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6e3a9b68 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6e3a9b68 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6e3a9b68 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6e3a9b68 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6e3a9b68 start_wqthread + 0

Thread 9 Crashed:: SPDataImport background import task (SPDatabaseDocument#1)
0   libobjc.A.dylib               	0x00007fff6cff7678 objc_release + 24
1   libobjc.A.dylib               	0x00007fff6d013054 AutoreleasePoolPage::releaseUntil(objc_object**) + 134
2   libobjc.A.dylib               	0x00007fff6cff7dba objc_autoreleasePoolPop + 175
3   libobjc.A.dylib               	0x00007fff6d0131d0 AutoreleasePoolPage::tls_dealloc(void*) + 98
4   libsystem_pthread.dylib       	0x00007fff6e3ac054 _pthread_tsd_cleanup + 551
5   libsystem_pthread.dylib       	0x00007fff6e3ae512 _pthread_exit + 70
6   libsystem_pthread.dylib       	0x00007fff6e3abe08 pthread_exit + 42
7   com.apple.Foundation          	0x00007fff36a68fab +[NSThread exit] + 11
8   com.apple.Foundation          	0x00007fff369d67b6 __NSThread__start__ + 1084
9   libsystem_pthread.dylib       	0x00007fff6e3ae109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6e3a9b8b thread_start + 15

Thread 10:
0   libobjc.A.dylib               	0x00007fff6cff5800 objc_msgSend + 0
1   com.apple.Foundation          	0x00007fff36a41149 -[NSCompoundPredicate evaluateWithObject:substitutionVariables:] + 139
2   com.apple.Foundation          	0x00007fff36a12bb0 _filterObjectsUsingPredicate + 270
3   com.apple.Foundation          	0x00007fff36a6e259 -[NSMutableArray(NSPredicateSupport) filterUsingPredicate:] + 194
4   com.sequel-ace.sequel-ace     	0x00000001049a47b9 0x104861000 + 1324985
5   com.apple.Foundation          	0x00007fff369d67a2 __NSThread__start__ + 1064
6   libsystem_pthread.dylib       	0x00007fff6e3ae109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6e3a9b8b thread_start + 15

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff6e2ed756 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6e270eea nanosleep + 196
2   libsystem_c.dylib             	0x00007fff6e270de4 usleep + 53
3   com.sequel-ace.sequel-ace     	0x00000001049a59c0 0x104861000 + 1329600
4   com.sequel-ace.sequel-ace     	0x00000001049a3c8b 0x104861000 + 1322123
5   com.apple.Foundation          	0x00007fff369d67a2 __NSThread__start__ + 1064
6   libsystem_pthread.dylib       	0x00007fff6e3ae109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6e3a9b8b thread_start + 15

Thread 9 crashed with X86 Thread State (64-bit):
  rax: 0x00007c2c4328ddd0  rbx: 0x00007feac1338000  rcx: 0x00007feac1338090  rdx: 0x000000006a80a003
  rdi: 0x0000600001fdddd0  rsi: 0x000060000222c060  rbp: 0x000070000756ec50  rsp: 0x000070000756ec28
   r8: 0x0000000000000154   r9: 0x00000000000007fb  r10: 0x0000000000000060  r11: 0x0000000000000030
  r12: 0x0000000000000000  r13: 0x000070000756f000  r14: 0x00007feac1338038  r15: 0xa3a3a3a3a3a3a3a3
  rip: 0x00007fff6cff7678  rfl: 0x0000000000010202  cr2: 0x00007c2c4328ddf0
  
Logical CPU:     4
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Binary Images:
       0x104861000 -        0x104a2bfe7 +com.sequel-ace.sequel-ace (2.0.1 - 2029) <59720D3A-0145-34FB-B9D7-734A563FBBE0> /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
       0x104abc000 -        0x104ac9fff +com.sequel-ace.net.wafflesoftware.ShortcutRecorder.framework.Leopard (1.0) <9742B1FC-92D8-31B6-AF58-24AA59896062> /Applications/Sequel Ace.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder
       0x104adc000 -        0x104adffff +com.sequel-ace.querykit (1.0 - 1) <934862C6-5A3E-3637-B525-B7AFF1E0EE9D> /Applications/Sequel Ace.app/Contents/Frameworks/QueryKit.framework/Versions/A/QueryKit
       0x104af0000 -        0x104b0bfff +com.positivespinmedia.PSMTabBarFramework (2.0 - 2029) <91773E03-BA4E-3908-A28E-B13B9DA60435> /Applications/Sequel Ace.app/Contents/Frameworks/PSMTabBar.framework/Versions/A/PSMTabBar
       0x104b2a000 -        0x104ea2fff +com.sequel-ace.spmysql (1.0 - 1) <0F93E9BE-D66F-35AC-B3E7-DEF6C81140DE> /Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/SPMySQL
       0x106a83000 -        0x106b14eff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld
       0x108ca9000 -        0x108cac047  libobjc-trampolines.dylib (787.1) <8212B354-A106-3806-A022-A60F2B2FA5C9> /usr/lib/libobjc-trampolines.dylib
    0x7fff273b6000 -     0x7fff27603ff8  com.apple.RawCamera.bundle (9.02.0 - 1350.29) <0CC24FF1-0754-3A75-BA2D-212CF70ADDC1> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff27a77000 -     0x7fff27cecff5  com.apple.AMDRadeonX6000MTLDriver (3.9.15 - 3.0.9) <7B8AB1A2-CEC5-3787-9F3E-579CB73ABC64> /System/Library/Extensions/AMDRadeonX6000MTLDriver.bundle/Contents/MacOS/AMDRadeonX6000MTLDriver
    0x7fff2ccc8000 -     0x7fff2d0c7ff1  com.apple.driver.AppleIntelKBLGraphicsMTLDriver (14.6.18 - 14.0.6) <568AB53D-A275-3FAC-932C-A32C3E277CA3> /System/Library/Extensions/AppleIntelKBLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsMTLDriver
    0x7fff2fb67000 -     0x7fff2fd62ffb  com.apple.avfoundation (2.0 - 1850.2) <4820F165-5E20-3120-913D-C047FDB68392> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff2fd63000 -     0x7fff2fe2fffe  com.apple.audio.AVFAudio (1.0 - 415.72) <C0FE6926-F8E6-339A-9D11-C6E3BEE688BF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/Frameworks/AVFAudio.framework/Versions/A/AVFAudio
    0x7fff2ff4f000 -     0x7fff2ff4ffff  com.apple.Accelerate (1.11 - Accelerate 1.11) <56DFF715-6A4E-3231-BDCC-A348BCB05047> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2ff50000 -     0x7fff2ff66fef  libCGInterfaces.dylib (524.2.1) <A423F932-C044-3CEB-BF20-BF4CB323361E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff2ff67000 -     0x7fff305bdfff  com.apple.vImage (8.1 - 524.2.1) <17C93AB9-1625-3FDB-9851-C5E77BBE3428> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff305be000 -     0x7fff30825ff7  libBLAS.dylib (1303.60.1) <CBC28BE4-3C78-3AED-9565-0D625251D121> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff30826000 -     0x7fff30cf9fef  libBNNS.dylib (144.100.2) <8D653678-1F9B-3670-AAE2-46DFB8D37643> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff30cfa000 -     0x7fff31095fff  libLAPACK.dylib (1303.60.1) <F8E9D081-7C60-32EC-A47D-2D30CAD73C5F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff31096000 -     0x7fff310abfec  libLinearAlgebra.dylib (1303.60.1) <D2C1ACEA-2B6A-339A-9EEB-62A76CC92CBE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff310ac000 -     0x7fff310b1ff3  libQuadrature.dylib (7) <3112C977-8306-3190-8313-01A952B7F3CF> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff310b2000 -     0x7fff31122fff  libSparse.dylib (103) <40510BF9-99A7-3155-A81D-6DE5A0C73EDC> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff31123000 -     0x7fff31135fef  libSparseBLAS.dylib (1303.60.1) <3C1066AB-20D5-38D2-B1F2-70A03DE76D0B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff31136000 -     0x7fff3130dfd7  libvDSP.dylib (735.121.1) <74702E2E-ED05-3765-B18C-64BEFF62B517> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff3130e000 -     0x7fff313d0fef  libvMisc.dylib (735.121.1) <137558BF-503D-3A6E-96DC-A181E3FB31FF> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff313d1000 -     0x7fff313d1fff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <D7E8E400-35C8-3174-9956-8D1B483620DA> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff313d2000 -     0x7fff31431ff0  com.apple.Accounts (113 - 113) <0510C893-F1F2-38B2-B3AA-A30DB2F5B688> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fff3157b000 -     0x7fff3233bffd  com.apple.AppKit (6.9 - 1894.50.103) <61269B8C-C432-335F-8894-B95C235A41A5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3238b000 -     0x7fff3238bfff  com.apple.ApplicationServices (48 - 50) <EEC73694-1A37-3C14-A839-6991E2BD8655> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3238c000 -     0x7fff323f7fff  com.apple.ApplicationServices.ATS (377 - 493.0.4.1) <A6912C4A-55CC-3701-BACA-E63423B99481> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff32490000 -     0x7fff324ceff0  libFontRegistry.dylib (274.0.5.1) <A78A7869-C96C-3AD6-A038-DE541639BB60> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff32529000 -     0x7fff32558fff  com.apple.ATSUI (1.0 - 1) <4B3C2201-DBB3-352C-936B-9C423122EFF6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/ATSUI
    0x7fff32559000 -     0x7fff3255dffb  com.apple.ColorSyncLegacy (4.13.0 - 1) <47D42CDE-2E9A-3AF6-9365-1BFD1189196B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff325f7000 -     0x7fff3264effa  com.apple.HIServices (1.22 - 675.1) <273492E3-FF0F-3A8A-A83F-0F11F99B5F26> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff3264f000 -     0x7fff3265dfff  com.apple.LangAnalysis (1.7.0 - 1.7.0) <DA175323-5BE3-3C54-92D4-A171A4A067E6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff3265e000 -     0x7fff326a3ffa  com.apple.print.framework.PrintCore (15.4 - 516.2) <99AEBCDB-2DCA-3A13-906F-7F0D7962B002> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff326a4000 -     0x7fff326aeff7  com.apple.QD (4.0 - 413) <D2E1DC80-D26F-3508-BBA5-B8AE7ED6CB0E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff326af000 -     0x7fff326bcffc  com.apple.speech.synthesis.framework (9.0.24 - 9.0.24) <823C0DE7-1351-3B39-8F06-AB5FCAD2C874> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff326bd000 -     0x7fff3279effa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <75651F0A-F2CE-3F68-B86A-E66B8815DCF4> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff327a0000 -     0x7fff327a0fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <E51DCB3C-CF4F-320B-AC86-D445E30C0891> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff32b36000 -     0x7fff32ec4ffd  com.apple.CFNetwork (1126 - 1126) <BB8F4C63-10B8-3ACD-84CF-D4DCFA9245DD> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff32f40000 -     0x7fff32f40fff  com.apple.Carbon (160 - 162) <4F1F60CB-6C1E-3D79-832E-8D606601F282> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff32f41000 -     0x7fff32f44ff3  com.apple.CommonPanels (1.2.6 - 101) <333BBF55-AF23-3B99-A9FF-7906175B9406> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff32f45000 -     0x7fff33239ff3  com.apple.HIToolbox (2.1.1 - 994.6) <5C44ACA7-D158-3F9B-8F88-0477510D44FA> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff3323a000 -     0x7fff3323dff3  com.apple.help (1.3.8 - 71) <4B2701A0-8813-35F8-82F8-676B184D15C4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff3323e000 -     0x7fff33243ff7  com.apple.ImageCapture (9.0 - 1600.60.4.2) <20872A2D-CBF9-38E6-BD16-C1D387120651> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff33244000 -     0x7fff33244fff  com.apple.ink.framework (10.15 - 227) <5B60FDDE-D60E-326B-BD3D-6EA5FA1CBB76> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff33245000 -     0x7fff3325fffa  com.apple.openscripting (1.7 - 185.1) <E59F893B-1A73-3098-8924-79227EC9787E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff33280000 -     0x7fff33280fff  com.apple.print.framework.Print (15 - 271) <07C50BF6-2222-3769-A5B8-79D7F996183F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff33281000 -     0x7fff33283ff7  com.apple.securityhi (9.0 - 55008) <D7017D5A-4206-3E2F-9F8E-0F932422CA87> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff33284000 -     0x7fff3328afff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <1188E643-967C-334E-BC1A-60A0F82C67E5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff3328b000 -     0x7fff33423ffa  com.apple.cloudkit.CloudKit (867 - 867) <C68C376E-E2CF-34FE-BC1F-B254233F980D> /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
    0x7fff33424000 -     0x7fff33424fff  com.apple.Cocoa (6.11 - 23) <87426C3A-7C6C-39D0-905C-C591B997029E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff33432000 -     0x7fff33528fff  com.apple.ColorSync (4.13.0 - 3394.9) <61698A7B-BB8C-3891-9547-703FF84671A8> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff33813000 -     0x7fff33d1cffb  com.apple.audio.CoreAudio (5.0 - 5.0) <62BEE4B7-8A26-3951-9D78-4E193617AF7A> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff33d6f000 -     0x7fff33da7fff  com.apple.CoreBluetooth (1.0 - 1) <6BC7F863-4495-371F-BC54-543E5CFE1665> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff33da8000 -     0x7fff34192fe8  com.apple.CoreData (120 - 977.3) <D902A2E3-1D0A-3995-974E-A526976E5735> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff34193000 -     0x7fff342c3ffe  com.apple.CoreDisplay (1.0 - 186.6.12) <EA74CC46-8715-3B90-95E8-4594D2F0CC8A> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff342c4000 -     0x7fff34743ffb  com.apple.CoreFoundation (6.9 - 1676.105) <6AF8B3CC-BC3F-3869-B9FB-1D881422364E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff34745000 -     0x7fff34db9ff8  com.apple.CoreGraphics (2.0 - 1355.17) <E1CE3919-F36B-309F-89BA-79F36DC8125E> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff34dc7000 -     0x7fff35122ff0  com.apple.CoreImage (15.0.0 - 940.9) <44F68E8C-315A-32A6-BB19-7F24C00AB347> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff35123000 -     0x7fff3518cff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <B1E3382A-62ED-36F0-AB86-F46D7B7FF9AE> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff351e0000 -     0x7fff354e2ff2  com.apple.CoreML (1.0 - 1) <06598905-BA5B-3D89-9921-39C6D5889DD9> /System/Library/Frameworks/CoreML.framework/Versions/A/CoreML
    0x7fff354e3000 -     0x7fff355beffc  com.apple.CoreMedia (1.0 - 2620.11.40.2) <0F490101-ED30-3189-B099-E247B6361A0B> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff355bf000 -     0x7fff35621ffe  com.apple.CoreMediaIO (1000.0 - 5125.6) <9435B82E-4728-362C-9FF0-E8AEC19D6E3C> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
    0x7fff356ab000 -     0x7fff356abfff  com.apple.CoreServices (1069.24 - 1069.24) <D9F6AB40-10EC-3682-A969-85560E2E4768> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff356ac000 -     0x7fff35731fff  com.apple.AE (838.1 - 838.1) <5F26DA9B-FB2E-3AF8-964B-63BD6671CF12> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff35732000 -     0x7fff35a13ff7  com.apple.CoreServices.CarbonCore (1217 - 1217) <8022AF47-AA99-3786-B086-141D84F00387> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff35a14000 -     0x7fff35a61ffd  com.apple.DictionaryServices (1.2 - 323.6) <C0F3830C-A4C6-3046-9A6A-DE1B5D448C2C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff35a62000 -     0x7fff35a6aff7  com.apple.CoreServices.FSEvents (1268.100.1 - 1268.100.1) <E4B2CAF2-1203-335F-9971-1278CB6E2AE0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff35a6b000 -     0x7fff35ca5ff6  com.apple.LaunchServices (1069.24 - 1069.24) <2E0AD228-B1CC-3645-91EE-EB7F46F2147B> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff35ca6000 -     0x7fff35d3eff1  com.apple.Metadata (10.7.0 - 2076.6) <C8034E84-7DD4-34B9-9CDF-16A05032FF39> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff35d3f000 -     0x7fff35d6cfff  com.apple.CoreServices.OSServices (1069.24 - 1069.24) <72FDEA52-7607-3745-AC43-630D80962099> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff35d6d000 -     0x7fff35dd4fff  com.apple.SearchKit (1.4.1 - 1.4.1) <086EB5DF-A2EC-3342-8028-CA7996BE5CB2> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff35dd5000 -     0x7fff35df9ff5  com.apple.coreservices.SharedFileList (131.4 - 131.4) <AE333DA2-C279-3751-8C15-B963E58EE61E> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff36056000 -     0x7fff3611dffc  com.apple.CoreTelephony (113 - 7560.1) <BAC6EEA9-89A0-3D03-BE0B-C65A3838C9D0> /System/Library/Frameworks/CoreTelephony.framework/Versions/A/CoreTelephony
    0x7fff3611e000 -     0x7fff362d5ffc  com.apple.CoreText (643.1.5.1 - 643.1.5.1) <715FE3F7-E8FB-3997-85A0-3AB2839F6C30> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff362d6000 -     0x7fff3631affb  com.apple.CoreVideo (1.8 - 344.3) <A200AFC7-2CB2-30CD-8B2A-1269CA64A29B> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff3631b000 -     0x7fff363a8ffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <855E51AA-DF3A-3BB9-A4F0-6880D42B8762> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff36564000 -     0x7fff3656fff7  com.apple.DirectoryService.Framework (10.15 - 220.40.1) <06D98FD0-796F-356F-B492-A6D8F3D5BEC0> /System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryService
    0x7fff36570000 -     0x7fff3661aff0  com.apple.DiscRecording (9.0.3 - 9030.4.5) <D9033DDA-E4C8-36FB-AE60-4EF66F4F1F9E> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff3663f000 -     0x7fff36645fff  com.apple.DiskArbitration (2.7 - 2.7) <52E7D181-2A18-37CD-B24F-AA32E93F7A69> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff36838000 -     0x7fff36966ff6  com.apple.FileProvider (304.1 - 304.1) <58D64236-947E-3E6A-85E6-C66AEF9E0EE0> /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider
    0x7fff3697e000 -     0x7fff36d43fff  com.apple.Foundation (6.9 - 1676.105) <1FA28BAB-7296-3A09-8E1E-E62A7D233DB8> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff36db0000 -     0x7fff36e00ff7  com.apple.GSS (4.0 - 2.0) <4E241C00-42A5-3572-9430-D950FBB7A4A0> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff36f3d000 -     0x7fff37051ff3  com.apple.Bluetooth (7.0.5 - 7.0.5f6) <5897C368-9674-3E34-B144-FFB06A2DF37B> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff370b7000 -     0x7fff3715bff3  com.apple.framework.IOKit (2.0.2 - 1726.121.1) <A0F54725-036F-3279-A46E-C2ABDBFD479B> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3715d000 -     0x7fff3716effb  com.apple.IOSurface (269.11 - 269.11) <D3CC2AA1-4AE2-30EE-A9DB-C04CCAA88ADE> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff3718c000 -     0x7fff371ecff7  com.apple.ImageCaptureCore (1.0 - 1600.60.4.2) <8BA11284-66A0-3567-A13C-72AD1CC0C2EA> /System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore
    0x7fff371ed000 -     0x7fff37349ffe  com.apple.ImageIO.framework (3.3.0 - 1976.6) <5B4C2E04-9161-3C82-A7FB-F4D51E3C1E10> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3734a000 -     0x7fff3734dfff  libGIF.dylib (1976.6) <3B26EE1C-C570-305C-A9A3-EA62D2F2E7B8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff3734e000 -     0x7fff37407fff  libJP2.dylib (1976.6) <EB4E4E09-DD81-3E6B-A513-3667E810AEF3> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff37408000 -     0x7fff3742bfe3  libJPEG.dylib (1976.6) <9D7FAC55-85A6-34AB-9F26-0BCA381E8CE7> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff376a7000 -     0x7fff376c1fef  libPng.dylib (1976.6) <4886A1F8-E9CA-38F2-BF2F-1FCA1DFDD1C9> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff376c2000 -     0x7fff376c3fff  libRadiance.dylib (1976.6) <FA759D33-131A-33B8-943E-32409F162738> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff376c4000 -     0x7fff3770dfff  libTIFF.dylib (1976.6) <E9994BF8-6CF5-3422-B4FD-A14DC390EF12> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff37726000 -     0x7fff37bb5ff8  com.apple.Intents (1.0 - 1) <EA4EEE84-D337-3C59-9C02-261205CA04E7> /System/Library/Frameworks/Intents.framework/Versions/A/Intents
    0x7fff37bb8000 -     0x7fff38c58fe9  com.apple.JavaScriptCore (15609 - 15609.2.9.1.2) <62158DFB-C250-3A18-AE52-6296544AEA43> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff38c6f000 -     0x7fff38c81ff3  com.apple.Kerberos (3.0 - 1) <AE0E56CA-D924-3CC8-BBAA-8C6EEC3038BE> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff38c82000 -     0x7fff38c82fff  libHeimdalProxy.dylib (77) <A970C7A8-7CCD-3701-A459-078BD5E8FE4E> /System/Library/Frameworks/Kerberos.framework/Versions/A/Libraries/libHeimdalProxy.dylib
    0x7fff38c83000 -     0x7fff38cb9ff7  com.apple.LDAPFramework (2.4.28 - 194.5) <4CFB6351-53B9-36AF-B654-AE636BBC361A> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
    0x7fff39014000 -     0x7fff3901effb  com.apple.MediaAccessibility (1.0 - 125.1) <DBF40A12-65A6-33E4-839C-292600B7D910> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff390ea000 -     0x7fff39837ff5  com.apple.MediaToolbox (1.0 - 2620.11.40.2) <40F16AF6-79D1-3C2E-976C-E7E7870A4EF9> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff39839000 -     0x7fff39903ff7  com.apple.Metal (212.7 - 212.7) <CC7BF715-142B-3C2A-81AD-0E35693230F2> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff39905000 -     0x7fff3991fff5  com.apple.MetalKit (141.2 - 141.2) <8162AFB6-327C-3BE1-AEF7-2BEA999B1DFB> /System/Library/Frameworks/MetalKit.framework/Versions/A/MetalKit
    0x7fff39920000 -     0x7fff3995dff7  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <52089325-EC97-3EED-ABB3-9B39EC0BD429> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff3995e000 -     0x7fff399e8fe2  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <9E434EA0-6BCA-3903-B882-CEB69730A63B> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff399e9000 -     0x7fff39a0eff4  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <EDD6C3A5-E231-3FB1-B4D4-45742AFB9A4E> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff39a0f000 -     0x7fff39a24ffb  com.apple.MetalPerformanceShaders.MPSNDArray (1.0 - 1) <C5A2B865-5CE2-3E5D-8452-54639FCB0954> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray
    0x7fff39a25000 -     0x7fff39b83ffc  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <47CCDBAC-5843-366A-A68C-6E8851D0865D> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff39b84000 -     0x7fff39bd3ff4  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <302BDF8E-B00A-3123-A6C4-E262B7513CF6> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff39bd4000 -     0x7fff39bd5ff5  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <14F84B42-9DA2-39A1-81B4-666B8020520C> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff3ac5c000 -     0x7fff3ac68ffe  com.apple.NetFS (6.0 - 4.0) <AC74E6A4-6E9B-3AB1-9577-8277F8A3EDE0> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff3ac69000 -     0x7fff3adc0ff3  com.apple.Network (1.0 - 1) <B5B8E999-BBCC-3DEF-8881-8FFF69F8EC4B> /System/Library/Frameworks/Network.framework/Versions/A/Network
    0x7fff3adc1000 -     0x7fff3b020ff5  com.apple.NetworkExtension (1.0 - 1) <446D0D36-E8F8-3F2C-B32B-5C3630177FBC> /System/Library/Frameworks/NetworkExtension.framework/Versions/A/NetworkExtension
    0x7fff3d7f1000 -     0x7fff3d849fff  com.apple.opencl (3.5 - 3.5) <9B101D40-EA79-3C0D-B7AE-A3F18094B2D7> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff3d84a000 -     0x7fff3d866fff  com.apple.CFOpenDirectory (10.15 - 220.40.1) <BFC32EBE-D95C-3267-B95C-5CEEFD189EA6> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff3d867000 -     0x7fff3d872ffd  com.apple.OpenDirectory (10.15 - 220.40.1) <76A20BBA-775F-3E17-AB0F-FEDFCDCE0716> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff3e1d8000 -     0x7fff3e1dafff  libCVMSPluginSupport.dylib (17.10.22) <AAE07E0C-4B28-364B-A7D9-028C7CD14954> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff3e1db000 -     0x7fff3e1e0fff  libCoreFSCache.dylib (176.15) <609C5DFC-9A97-344D-BBC7-E0B08D862C63> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff3e1e1000 -     0x7fff3e1e5fff  libCoreVMClient.dylib (176.15) <8F8DD27F-AC7C-398D-A8E3-396F1528E317> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff3e1e6000 -     0x7fff3e1eeff7  libGFXShared.dylib (17.10.22) <D0649AB5-5331-328D-8141-E5A6F06D4AD7> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff3e1ef000 -     0x7fff3e1f9fff  libGL.dylib (17.10.22) <116DDBF7-D725-3B8C-BD0B-A21B758FE421> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff3e1fa000 -     0x7fff3e22eff7  libGLImage.dylib (17.10.22) <2B314C76-C7E6-3AC5-9157-70B0529C1F9B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff3e3c4000 -     0x7fff3e400fff  libGLU.dylib (17.10.22) <B29F73B2-B5A9-3C38-AF77-351173D2E3DB> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff3ee3c000 -     0x7fff3ee4bff7  com.apple.opengl (17.10.22 - 17.10.22) <D5BF32A8-2E0A-345D-80A3-7CA7C2CF748D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff3effd000 -     0x7fff3f0f0ff0  com.apple.PDFKit (1.0 - 835.7) <346881D8-3E09-3787-B877-6284D1D3B24A> /System/Library/Frameworks/PDFKit.framework/Versions/A/PDFKit
    0x7fff3f0f1000 -     0x7fff3f208ff9  com.apple.PencilKit (1.0 - 1) <AD3C6D86-17D6-35A3-AE5C-BEDB872197BF> /System/Library/Frameworks/PencilKit.framework/Versions/A/PencilKit
    0x7fff3f4a9000 -     0x7fff3f4afff6  com.apple.PushKit (1.0 - 1) <B4E45366-8C51-3248-BDAF-2ECFE94D5378> /System/Library/Frameworks/PushKit.framework/Versions/A/PushKit
    0x7fff3f5d0000 -     0x7fff3f816ff7  com.apple.imageKit (3.0 - 1081) <F0AD8D71-D6BE-3ABC-9B5F-93825F3F96B1> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
    0x7fff3f817000 -     0x7fff3fcd6fff  com.apple.QuartzComposer (5.1 - 378) <351442B3-92C1-30FB-B5BC-E64759CCA5FC> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
    0x7fff3fcd7000 -     0x7fff3fcfcffc  com.apple.quartzfilters (1.10.0 - Tag) <F491CB46-3837-3525-AE31-23EB89692BA1> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzFilters.framework/Versions/A/QuartzFilters
    0x7fff3fcfd000 -     0x7fff3fe07ff7  com.apple.QuickLookUIFramework (5.0 - 906.2) <731A1F57-2064-3941-823E-2D23BD1D9CB1> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
    0x7fff3fe08000 -     0x7fff3fe08fff  com.apple.quartzframework (1.5 - 23) <E2368AAF-5B01-328F-9D5D-9089CBB9C8FA> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff3fe09000 -     0x7fff4008bff9  com.apple.QuartzCore (1.11 - 841.2) <444E6F22-DFA6-391B-B51F-A96AE69E524D> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff4008c000 -     0x7fff400e5ff5  com.apple.QuickLookFramework (5.0 - 906.2) <E6F25D56-E003-3B3B-851B-1566C132E006> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff400e6000 -     0x7fff4011bffc  com.apple.QuickLookThumbnailing (1.0 - 1) <469201A4-C87A-335F-91C1-81055CF89844> /System/Library/Frameworks/QuickLookThumbnailing.framework/Versions/A/QuickLookThumbnailing
    0x7fff405ec000 -     0x7fff40604ff0  com.apple.SafariServices.framework (15609 - 15609.2.9.1.2) <DBB58DF1-3DA2-3558-B185-B7DAAB005113> /System/Library/Frameworks/SafariServices.framework/Versions/A/SafariServices
    0x7fff40c0c000 -     0x7fff40f55ff1  com.apple.security (7.0 - 59306.120.7) <AEA33464-1507-36F1-8CAE-A86EB787F9B5> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff40f56000 -     0x7fff40fdeffb  com.apple.securityfoundation (6.0 - 55236.60.1) <79289FE1-CB5F-3BEF-A33F-11A29A93A681> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff40fdf000 -     0x7fff4100cff7  com.apple.securityinterface (10.0 - 55139.120.1) <CBC1CC5B-6C24-3843-935F-052767FBB69D> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff4100d000 -     0x7fff41011ff8  com.apple.xpc.ServiceManagement (1.0 - 1) <4194D29D-F0D4-33F8-839A-D03C6C62D8DB> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff41cbd000 -     0x7fff41d2bff7  com.apple.SystemConfiguration (1.19 - 1.19) <0CF8726A-BE41-3E07-B895-FBC44B75450E> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff41faa000 -     0x7fff4232dff4  com.apple.VideoToolbox (1.0 - 2620.11.40.2) <53E0D852-61CA-34FE-9A9B-788708ADE495> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff425cf000 -     0x7fff42d6cfff  libwebrtc.dylib (7609.2.9.1.2) <6047B7DA-1F79-35D6-B65B-F936B0E389EE> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libwebrtc.dylib
    0x7fff42d6d000 -     0x7fff44fceff4  com.apple.WebCore (15609 - 15609.2.9.1.2) <06B06644-07F9-3D09-A50E-F14D70FF6670> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
    0x7fff44fcf000 -     0x7fff451dbffc  com.apple.WebKitLegacy (15609 - 15609.2.9.1.2) <7580EF1B-F43B-3532-9340-AB20340D0850> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
    0x7fff451dc000 -     0x7fff458ddffa  com.apple.WebKit (15609 - 15609.2.9.1.2) <5148A4E2-0C5A-3DFD-8A02-676D7CC6ED4F> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff45c8c000 -     0x7fff45d51ff7  com.apple.APFS (1412.120.2 - 1412.120.2) <1E8FD511-FDC4-31A2-ACDE-EB5192032BC6> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff46398000 -     0x7fff463a3ffc  com.apple.accessibility.AXCoreUtilities (1.0 - 1) <9E0367E6-6A4F-31FE-A493-9F3DF7510CA0> /System/Library/PrivateFrameworks/AXCoreUtilities.framework/Versions/A/AXCoreUtilities
    0x7fff46e61000 -     0x7fff46e62ff1  com.apple.AggregateDictionary (1.0 - 1) <B907CE7A-0122-3E63-BF39-0A242B0DD7C4> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff4712d000 -     0x7fff47278ff5  com.apple.AnnotationKit (1.0 - 325.9) <E9B0F74B-CB16-3E07-9015-8CBF158EB08D> /System/Library/PrivateFrameworks/AnnotationKit.framework/Versions/A/AnnotationKit
    0x7fff47279000 -     0x7fff47296ff4  com.apple.AppContainer (4.0 - 448.100.6) <9C2D0065-9B38-3D1C-A090-46F129A1B3CA> /System/Library/PrivateFrameworks/AppContainer.framework/Versions/A/AppContainer
    0x7fff472eb000 -     0x7fff472f9ff7  com.apple.AppSandbox (4.0 - 448.100.6) <7DAB58B1-8176-3FB0-A7B0-8A38E118E90B> /System/Library/PrivateFrameworks/AppSandbox.framework/Versions/A/AppSandbox
    0x7fff47774000 -     0x7fff47798ffb  com.apple.framework.Apple80211 (13.0 - 1610.1) <B4B80CD6-B38E-3748-B30B-5088CCE9A7A8> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff47a56000 -     0x7fff47a65fd7  com.apple.AppleFSCompression (119.100.1 - 1.0) <2E75CF51-B693-3275-9A4F-40571D48745E> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff47b64000 -     0x7fff47b6fff7  com.apple.AppleIDAuthSupport (1.0 - 1) <F4651654-E24F-3BF4-8DDF-8F91E5219BA4> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff47bb1000 -     0x7fff47bf9ff7  com.apple.AppleJPEG (1.0 - 1) <4655FF70-9772-3D7C-8159-5A5E56C9F84B> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff47fbc000 -     0x7fff47fe2ffb  com.apple.aps.framework (4.0 - 4.0) <34F0F991-2D0F-3376-B5B2-BDED2108552A> /System/Library/PrivateFrameworks/ApplePushService.framework/Versions/A/ApplePushService
    0x7fff47fe3000 -     0x7fff47fe7ff7  com.apple.AppleSRP (5.0 - 1) <B683AD55-A121-31DD-9A87-3A31C35FEABF> /System/Library/PrivateFrameworks/AppleSRP.framework/Versions/A/AppleSRP
    0x7fff47fe8000 -     0x7fff4800afff  com.apple.applesauce (1.0 - 16.25) <33B66B71-64A4-365D-9953-E0545E69A5E7> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff480c9000 -     0x7fff480ccffb  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <92580EE3-74BF-3488-90ED-C8EBD7A1B4C3> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fff480cd000 -     0x7fff4811dff7  com.apple.AppleVAFramework (6.1.2 - 6.1.2) <39C3583D-C824-3168-B67A-498487FD03D9> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff48166000 -     0x7fff48175ff9  com.apple.AssertionServices (1.0 - 223.100.31) <478D2004-9B84-3AE9-9A0B-0A0B68ED028F> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff486b7000 -     0x7fff48ab2ff8  com.apple.audio.AudioResourceArbitration (1.0 - 1) <9ABFE41A-FD01-3111-BA73-D2DD1BF96525> /System/Library/PrivateFrameworks/AudioResourceArbitration.framework/Versions/A/AudioResourceArbitration
    0x7fff48d08000 -     0x7fff48f48fe0  com.apple.audio.AudioToolboxCore (1.0 - 1104.84) <FA17E892-6A1A-309D-95C7-30ACFC44319C> /System/Library/PrivateFrameworks/AudioToolboxCore.framework/Versions/A/AudioToolboxCore
    0x7fff48f4c000 -     0x7fff49068ff0  com.apple.AuthKit (1.0 - 1) <375C3886-5430-3C02-BD2C-4244BF490ABA> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff49225000 -     0x7fff4922eff7  com.apple.coreservices.BackgroundTaskManagement (1.0 - 104) <F070F440-27AB-3FCF-9602-F278C332CA01> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff4922f000 -     0x7fff492d0ff5  com.apple.backup.framework (1.11.5 - 1298.5.10) <637CA389-627A-365C-98C2-D297C47D6EE3> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff492d1000 -     0x7fff4935dff6  com.apple.BaseBoard (466.3 - 466.3) <1718A41A-9923-3FD0-96B8-82376E153D27> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff4945f000 -     0x7fff4949bff7  com.apple.bom (14.0 - 219.2) <586F1D9C-23B0-3F38-9C5B-728E9DD8B953> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fff495b9000 -     0x7fff495f0ff5  com.apple.C2 (1.3 - 495) <4C624CDB-C2A8-3039-BC45-224FB8671969> /System/Library/PrivateFrameworks/C2.framework/Versions/A/C2
    0x7fff4a01a000 -     0x7fff4a069fff  com.apple.ChunkingLibrary (307 - 307) <32E0F1A1-9DD6-3B52-91C2-93643041AA60> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fff4af10000 -     0x7fff4af20ffb  com.apple.CommonAuth (4.0 - 2.0) <91EC83B5-857D-3D4F-93B1-AAD7E0E029D8> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff4af34000 -     0x7fff4af4bfff  com.apple.commonutilities (8.0 - 900) <12C6DEE5-1740-39A5-9711-6F815C6D77BD> /System/Library/PrivateFrameworks/CommonUtilities.framework/Versions/A/CommonUtilities
    0x7fff4b64f000 -     0x7fff4ba24fc8  com.apple.CoreAUC (283.0.0 - 283.0.0) <BA9522E5-95D0-30D0-BEF4-691CEB51035B> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff4ba25000 -     0x7fff4ba52ff7  com.apple.CoreAVCHD (6.1.0 - 6100.4.1) <14FC549B-86BD-396A-B03E-6F5219482943> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff4ba75000 -     0x7fff4ba94ffc  com.apple.analyticsd (1.0 - 1) <A4F653CA-2FD6-348B-B7B3-48D91A67508A> /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics
    0x7fff4bb9d000 -     0x7fff4bc13ff7  com.apple.corebrightness (1.0 - 1) <D1E20AF2-A96B-318C-9605-9A3BD6EC27C2> /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness
    0x7fff4bd9f000 -     0x7fff4bdaaff7  com.apple.frameworks.CoreDaemon (1.3 - 1.3) <8F8E586D-C153-3ABA-88B7-6CEC7F476F0E> /System/Library/PrivateFrameworks/CoreDaemon.framework/Versions/B/CoreDaemon
    0x7fff4bdab000 -     0x7fff4bfb6ff1  com.apple.CoreDuet (1.0 - 1) <C933EE99-D7D2-32F8-8B96-938A0FB612FB> /System/Library/PrivateFrameworks/CoreDuet.framework/Versions/A/CoreDuet
    0x7fff4bfb7000 -     0x7fff4c004ff3  com.apple.coreduetcontext (1.0 - 1) <64FD6DBA-89E3-34FC-A758-3240D4737F75> /System/Library/PrivateFrameworks/CoreDuetContext.framework/Versions/A/CoreDuetContext
    0x7fff4c005000 -     0x7fff4c015ffe  com.apple.CoreDuetDaemonProtocol (1.0 - 1) <00D3E768-CBBF-36DE-B8D8-218F7B562F6F> /System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/Versions/A/CoreDuetDaemonProtocol
    0x7fff4c018000 -     0x7fff4c01afff  com.apple.CoreDuetDebugLogging (1.0 - 1) <DBE17F86-59D6-368D-AEF1-4BDF85D2E735> /System/Library/PrivateFrameworks/CoreDuetDebugLogging.framework/Versions/A/CoreDuetDebugLogging
    0x7fff4c02b000 -     0x7fff4c03bff3  com.apple.CoreEmoji (1.0 - 107.1) <CDCCB4B0-B98F-38E8-9568-C81320E756EB> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff4c1f1000 -     0x7fff4c33efff  com.apple.CoreHandwriting (161 - 1.2) <7F6BAABE-71D0-34F6-876D-C6C53331B5F3> /System/Library/PrivateFrameworks/CoreHandwriting.framework/Versions/A/CoreHandwriting
    0x7fff4c67b000 -     0x7fff4c6e5ff0  com.apple.CoreNLP (1.0 - 213) <40FC46D2-844C-3282-A8E4-69DD827F05C5> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff4c9a3000 -     0x7fff4c9a7ffb  com.apple.CoreOptimization (1.0 - 1) <5B3AA81A-F8DF-3688-85FC-9A9517720DA7> /System/Library/PrivateFrameworks/CoreOptimization.framework/Versions/A/CoreOptimization
    0x7fff4c9a8000 -     0x7fff4ca30ffe  com.apple.CorePDF (4.0 - 518.4.1) <98F39D44-028B-3714-AC76-0884D08DD6CF> /System/Library/PrivateFrameworks/CorePDF.framework/Versions/A/CorePDF
    0x7fff4cb13000 -     0x7fff4cb1bff8  com.apple.CorePhoneNumbers (1.0 - 1) <B2CE100D-B82F-3481-86F6-7F85FF8BFAFB> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff4cb1c000 -     0x7fff4cb6e94b  com.apple.CorePrediction (1.0 - 1) <CED11BE0-808C-39C5-9FCE-29368322E9B1> /System/Library/PrivateFrameworks/CorePrediction.framework/Versions/A/CorePrediction
    0x7fff4d508000 -     0x7fff4d52bfff  com.apple.CoreSVG (1.0 - 129) <3141D198-0507-3F72-A2C9-752EAFE3EEB3> /System/Library/PrivateFrameworks/CoreSVG.framework/Versions/A/CoreSVG
    0x7fff4d52c000 -     0x7fff4d55ffff  com.apple.CoreServicesInternal (446.7 - 446.7) <B2CEC515-2225-3CB1-B34A-904AAEA54FDF> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff4d560000 -     0x7fff4d58effd  com.apple.CSStore (1069.24 - 1069.24) <C96E5CE8-D604-3F13-B079-B2BA33B90081> /System/Library/PrivateFrameworks/CoreServicesStore.framework/Versions/A/CoreServicesStore
    0x7fff4dab3000 -     0x7fff4db49ff7  com.apple.CoreSymbolication (11.4 - 64535.33.2) <0E7A1529-C737-33FD-AA7D-A32EB8B192DA> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff4dbe1000 -     0x7fff4dd0dff6  com.apple.coreui (2.1 - 609.4) <9B93CC42-804B-305A-8FCE-5F06821B544C> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff4dd0e000 -     0x7fff4dec4ff5  com.apple.CoreUtils (6.2.1 - 621.5) <CD4B58E5-1494-3457-84FF-3869378E2DC9> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff4dffe000 -     0x7fff4e011ff1  com.apple.CrashReporterSupport (10.13 - 15016) <827F4E31-9F23-3683-AC5A-59CCA90F2359> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff4e0ca000 -     0x7fff4e0dcff8  com.apple.framework.DFRFoundation (1.0 - 252.50.1) <19F79D32-71D3-3A87-98C9-B5C6C96076C4> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff4e0dd000 -     0x7fff4e0e2fff  com.apple.DSExternalDisplay (3.1 - 380) <971F24F1-B1FC-3674-9C00-F88EEF94DC05> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff4e16c000 -     0x7fff4e1e6ff0  com.apple.datadetectorscore (8.0 - 659) <9FD9BDFA-3724-3BEA-946C-0473447196A3> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff4e232000 -     0x7fff4e26fff8  com.apple.DebugSymbols (194 - 194) <9BCE6685-6C45-3DF9-98EB-FCF8196160F0> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff4e270000 -     0x7fff4e3f8ff6  com.apple.desktopservices (1.14.5 - 1281.5.3) <79972B8B-7B60-3AD5-9A5F-17976DE8080B> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff4e40e000 -     0x7fff4e41aff8  com.apple.DeviceIdentity (1.0 - 1) <6E017199-DFC0-3464-A7E5-CB8928FC2F97> /System/Library/PrivateFrameworks/DeviceIdentity.framework/Versions/A/DeviceIdentity
    0x7fff4e67f000 -     0x7fff4e747ffe  com.apple.DiskImagesFramework (559.100.2 - 559.100.2) <DE281E96-21D0-3BE3-BEE0-D901B24D71EE> /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages
    0x7fff4e748000 -     0x7fff4e81bff1  com.apple.DiskManagement (13.0 - 1648.120.5) <650DBBE4-6624-3064-A26D-6BCAA0FE41F9> /System/Library/PrivateFrameworks/DiskManagement.framework/Versions/A/DiskManagement
    0x7fff4e81c000 -     0x7fff4e820ff1  com.apple.DisplayServicesFW (3.1 - 380) <A5F74849-D8E4-30DC-A638-BFD4332CD6AB> /System/Library/PrivateFrameworks/DisplayServices.framework/Versions/A/DisplayServices
    0x7fff4e87a000 -     0x7fff4e89eff9  com.apple.DuetActivityScheduler (1.0 - 1) <C63FCC5A-CF9B-31B0-B549-04FC4527B826> /System/Library/PrivateFrameworks/DuetActivityScheduler.framework/Versions/A/DuetActivityScheduler
    0x7fff4e8c8000 -     0x7fff4e8fdff7  com.apple.SystemConfiguration.EAP8021X (14.0.0 - 14.0) <E0BAD6DA-3F7C-32A4-AB32-13C9D604690B> /System/Library/PrivateFrameworks/EAP8021X.framework/Versions/A/EAP8021X
    0x7fff4e8fe000 -     0x7fff4e902ff9  com.apple.EFILogin (2.0 - 2) <B95015BC-5BC2-33D9-AD94-01905DD56193> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fff4f44b000 -     0x7fff4fab5ff9  com.apple.vision.EspressoFramework (1.0 - 188.4) <4502588F-70F2-3A5F-9089-4B2F29159961> /System/Library/PrivateFrameworks/Espresso.framework/Versions/A/Espresso
    0x7fff4fd90000 -     0x7fff501abff1  com.apple.vision.FaceCore (4.3.0 - 4.3.0) <1B5D7DD6-718E-3111-A702-EB04B8903662> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff50849000 -     0x7fff50981ffc  libFontParser.dylib (277.2.5.3) <DEB18756-082F-359B-AE93-F9C3B5EC7AF4> /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
    0x7fff50982000 -     0x7fff509b6fff  libTrueTypeScaler.dylib (277.2.5.3) <B16255A6-C51A-328B-B679-8FBF64495770> /System/Library/PrivateFrameworks/FontServices.framework/libTrueTypeScaler.dylib
    0x7fff50a1b000 -     0x7fff50a2bff6  libhvf.dylib (1.0 - $[CURRENT_PROJECT_VERSION]) <6396BC1F-13C1-37D7-91B9-1FF60910C7FA> /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib
    0x7fff53f0c000 -     0x7fff53f0dfff  libmetal_timestamp.dylib (902.14.11) <BE88F259-0A3C-3910-8983-FB5E2C905E87> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3902/Libraries/libmetal_timestamp.dylib
    0x7fff555ca000 -     0x7fff555d0fff  com.apple.GPUWrangler (5.2.4 - 5.2.4) <5B819701-9F0C-374B-8925-A22DFC16514F> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff558ef000 -     0x7fff55915ff1  com.apple.GenerationalStorage (2.0 - 314) <5613706F-710A-39E0-8B25-BA103A768613> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff5592e000 -     0x7fff56918ffc  com.apple.GeoServices (1.0 - 1624.24.10.29.41) <9A6FF368-7127-336F-9595-B261141810EA> /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
    0x7fff56a44000 -     0x7fff56a52ffb  com.apple.GraphVisualizer (1.0 - 100.1) <0A86C9FF-4484-3C7F-BC71-3D23BDBE81CE> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff56a53000 -     0x7fff56a60ff3  com.apple.GraphicsServices (1.0 - 1.0) <628EA7EF-A5C7-36E4-9193-46F55852C208> /System/Library/PrivateFrameworks/GraphicsServices.framework/Versions/A/GraphicsServices
    0x7fff56abb000 -     0x7fff56ac8ff9  com.apple.HID (1.0 - 1) <C750D8D3-C4DD-3E77-94B2-6A7B4D56DF2A> /System/Library/PrivateFrameworks/HID.framework/Versions/A/HID
    0x7fff56bf1000 -     0x7fff56cafff4  com.apple.Heimdal (4.0 - 2.0) <F2C504F6-E211-3AB0-9754-D96D2F96634B> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff576ac000 -     0x7fff576dbff8  com.apple.HelpData (2.3 - 199) <31ECA355-3529-3FD8-961A-5E5F70DAE1A8> /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/HelpData
    0x7fff58e29000 -     0x7fff58e32ffe  com.apple.IOAccelMemoryInfo (1.0 - 1) <903349F6-F3B0-3269-8946-2CE3E2C49E70> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff58e33000 -     0x7fff58e3bff5  com.apple.IOAccelerator (438.5.4 - 438.5.4) <A3CF45E0-4D88-33BF-BAEC-690D5664CDA0> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff58e48000 -     0x7fff58e5ffff  com.apple.IOPresentment (1.0 - 37) <3EDBB454-D248-394B-A026-9717CD8535C3> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff591e7000 -     0x7fff59232ff1  com.apple.IconServices (438.3 - 438.3) <2AE74790-64F1-3B0A-9534-DEEEE307E562> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff593cf000 -     0x7fff593ddfff  com.apple.IntentsFoundation (1.0 - 1) <C2C31BEB-FFCE-31E1-BA23-A093693C0BDC> /System/Library/PrivateFrameworks/IntentsFoundation.framework/Versions/A/IntentsFoundation
    0x7fff593f0000 -     0x7fff593f7ff9  com.apple.InternationalSupport (1.0 - 45.4) <C22AA77A-EDA6-3626-8816-521A8CD43C4A> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff59684000 -     0x7fff596a3ffd  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <76DB5326-BE5D-3339-975C-D9FCF39A341E> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff597d8000 -     0x7fff598a6ffd  com.apple.LanguageModeling (1.0 - 215.1) <A6FAA215-9A01-3EE1-B304-2238801C5883> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff598a7000 -     0x7fff598effff  com.apple.Lexicon-framework (1.0 - 72) <6AE1872C-0352-36FE-90CC-7303F13A5BEF> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff598f6000 -     0x7fff598fbff3  com.apple.LinguisticData (1.0 - 353.18) <686E7B7C-640F-3D7B-A9C1-31E2DFACD457> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff59922000 -     0x7fff59946ffe  com.apple.locationsupport (2394.0.22 - 2394.0.22) <5C15E3FF-D269-3A99-B3EF-B806F61EE1EA> /System/Library/PrivateFrameworks/LocationSupport.framework/Versions/A/LocationSupport
    0x7fff5999f000 -     0x7fff599a4ff7  com.apple.LoginUICore (4.0 - 4.0) <5D60C7D1-9DB7-30A3-9209-7E13644D3E9D> /System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/Frameworks/LoginUICore.framework/Versions/A/LoginUICore
    0x7fff5a193000 -     0x7fff5a196fff  com.apple.Mangrove (1.0 - 25) <11A30F47-B1C1-375E-9FE7-0A196E92A52C> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff5a354000 -     0x7fff5a37affc  com.apple.MarkupUI (1.0 - 325.9) <FB688EC0-67FD-37A2-BED0-A017F4FA029A> /System/Library/PrivateFrameworks/MarkupUI.framework/Versions/A/MarkupUI
    0x7fff5a3ff000 -     0x7fff5a489ff8  com.apple.MediaExperience (1.0 - 1) <34E15DA2-02AA-32FA-99E1-9A139521E226> /System/Library/PrivateFrameworks/MediaExperience.framework/Versions/A/MediaExperience
    0x7fff5a48a000 -     0x7fff5a4bdfff  com.apple.MediaKit (16 - 923) <14E38848-C9BD-37F1-AE44-FC4CC839E8A1> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fff5ac62000 -     0x7fff5acaefff  com.apple.spotlight.metadata.utilities (1.0 - 2076.6) <C3AEA22D-1FEB-3E38-9821-1FA447C8AF9D> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff5acaf000 -     0x7fff5ad80ffa  com.apple.gpusw.MetalTools (1.0 - 1) <A23FFAB6-437C-303C-A3E8-99F323F8E734> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff5adde000 -     0x7fff5adf7ff4  com.apple.MobileAssets (1.0 - 619.120.1) <5AF95641-68C7-351A-A317-3C7B793502D6> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff5afb4000 -     0x7fff5afd2fff  com.apple.MobileKeyBag (2.0 - 1.0) <B564179F-A5E9-3BD8-892D-CEF2BE0DA0D7> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff5b09e000 -     0x7fff5b234ffd  com.apple.Montreal (1.0 - 121.1) <9A9642A5-CE1F-3C1E-ACEF-C3CC789A1D26> /System/Library/PrivateFrameworks/Montreal.framework/Versions/A/Montreal
    0x7fff5b235000 -     0x7fff5b265ff7  com.apple.MultitouchSupport.framework (3440.1 - 3440.1) <4E7CB188-382E-3128-8671-4A3EF6E06622> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff5b765000 -     0x7fff5b76ffff  com.apple.NetAuth (6.2 - 6.2) <D660F2CB-5A49-3DD0-9DB3-86EF0797828C> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff5c185000 -     0x7fff5c1d0ffb  com.apple.OTSVG (1.0 - 643.1.5.1) <CD494F00-9AA4-3A48-916B-EA8661F9772D> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff5d3e4000 -     0x7fff5d3efff2  com.apple.PerformanceAnalysis (1.243.2 - 243.2) <941698D6-EF00-3D59-8560-F160BC04B412> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff5d3f0000 -     0x7fff5d418ffb  com.apple.persistentconnection (1.0 - 1.0) <FFC20BB6-9CF3-39F2-AE5C-8DEE348FE0C1> /System/Library/PrivateFrameworks/PersistentConnection.framework/Versions/A/PersistentConnection
    0x7fff5ee91000 -     0x7fff5eec1ff7  com.apple.pluginkit.framework (1.0 - 1) <6A417FEF-CEDE-3EE0-93ED-42680A31C886> /System/Library/PrivateFrameworks/PlugInKit.framework/Versions/A/PlugInKit
    0x7fff5eeec000 -     0x7fff5eeffffc  com.apple.PowerLog (1.0 - 1) <63A89A9B-2ACC-3378-9BD0-7FA971E07C2A> /System/Library/PrivateFrameworks/PowerLog.framework/Versions/A/PowerLog
    0x7fff5fd7b000 -     0x7fff5fdd5ff6  com.apple.ProtectedCloudStorage (1.0 - 1) <969BF7A2-E989-3A22-BC1B-72B72E107229> /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Versions/A/ProtectedCloudStorage
    0x7fff5fdd6000 -     0x7fff5fdefffb  com.apple.ProtocolBuffer (1 - 274.24.9.16.3) <A2E34123-7CED-378B-A43D-1B98B5B85F5C> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff5ff01000 -     0x7fff5ff04ff4  com.apple.QuickLookNonBaseSystem (1.0 - 1) <4579D418-9C34-3F29-B121-0046F2B87D0B> /System/Library/PrivateFrameworks/QuickLookNonBaseSystem.framework/Versions/A/QuickLookNonBaseSystem
    0x7fff5ff05000 -     0x7fff5ff28ff0  com.apple.quicklook.QuickLookSupport (1.0 - 1) <D4E71FA6-5776-304F-B007-51FFC81C6780> /System/Library/PrivateFrameworks/QuickLookSupport.framework/Versions/A/QuickLookSupport
    0x7fff5ff6f000 -     0x7fff5ffe8ff3  com.apple.Rapport (1.9.5 - 195.2) <6DB4EFB5-A70C-36AA-971B-3B728EEF41AB> /System/Library/PrivateFrameworks/Rapport.framework/Versions/A/Rapport
    0x7fff6022f000 -     0x7fff6023bff5  com.apple.xpc.RemoteServiceDiscovery (1.0 - 1738.120.8) <9754FC8C-3EAF-3F9B-8A28-A63D472DD6F0> /System/Library/PrivateFrameworks/RemoteServiceDiscovery.framework/Versions/A/RemoteServiceDiscovery
    0x7fff6024e000 -     0x7fff60277ff1  com.apple.RemoteViewServices (2.0 - 148) <1C61CFC2-F76F-31E5-BA13-EFD5DC69C8D5> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff60278000 -     0x7fff6028dffa  com.apple.xpc.RemoteXPC (1.0 - 1738.120.8) <BEC43C3B-D472-335D-8D4B-90DCACEC5758> /System/Library/PrivateFrameworks/RemoteXPC.framework/Versions/A/RemoteXPC
    0x7fff603dc000 -     0x7fff60417ff0  com.apple.RunningBoardServices (1.0 - 223.100.31) <9FD1FC53-186A-3327-A359-B0BC7F4360EF> /System/Library/PrivateFrameworks/RunningBoardServices.framework/Versions/A/RunningBoardServices
    0x7fff6113f000 -     0x7fff6118bff9  com.apple.Safari.SafeBrowsing (15609 - 15609.2.9.1.2) <57AC0345-D349-3477-9ECA-9BAD465819EA> /System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/Versions/A/SafariSafeBrowsing
    0x7fff61cf7000 -     0x7fff61cfaff5  com.apple.SecCodeWrapper (4.0 - 448.100.6) <813B3E57-6A95-3D7B-9094-C65D687A72B8> /System/Library/PrivateFrameworks/SecCodeWrapper.framework/Versions/A/SecCodeWrapper
    0x7fff61e6d000 -     0x7fff61f94ff0  com.apple.Sharing (1526.31 - 1526.31) <2CB07F08-7794-3BF2-9ED5-BAB5C55C9D2C> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff61fed000 -     0x7fff6200bff2  com.apple.shortcut (2.16 - 106) <51323823-C5EB-3EE0-AA81-8D633A3F75BD> /System/Library/PrivateFrameworks/Shortcut.framework/Versions/A/Shortcut
    0x7fff6200c000 -     0x7fff6202cff5  com.apple.sidecar-core (1.0 - 209.40.4) <A5BEBCF6-0B2F-3BA7-9F4C-A65E4AECB2E6> /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
    0x7fff6202d000 -     0x7fff6203fff0  com.apple.sidecar-ui (1.0 - 209.40.4) <55486B3A-B65A-3023-89C7-A154A39D0D7E> /System/Library/PrivateFrameworks/SidecarUI.framework/Versions/A/SidecarUI
    0x7fff633a7000 -     0x7fff6369dff7  com.apple.SkyLight (1.600.0 - 451.4) <F5B9065A-E975-36D1-8D53-9FBF02171FAB> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff63eea000 -     0x7fff63ef8ffb  com.apple.SpeechRecognitionCore (6.0.91.2 - 6.0.91.2) <820602AB-117B-3C3E-B20B-819CBC97B7A4> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff645d2000 -     0x7fff64613ff9  com.apple.StreamingZip (1.0 - 1) <EFCDDC94-28EE-3BCA-A105-0A928D15ED8C> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff6472a000 -     0x7fff64733ff7  com.apple.SymptomDiagnosticReporter (1.0 - 1238.120.1) <581F31D6-94CB-38AA-BD56-1A63606E516E> /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/Versions/A/SymptomDiagnosticReporter
    0x7fff647a4000 -     0x7fff647ceffa  com.apple.framework.SystemAdministration (1.0 - 1.0) <926BB2F5-E02C-30B7-949A-20EFE57CF242> /System/Library/PrivateFrameworks/SystemAdministration.framework/Versions/A/SystemAdministration
    0x7fff649ea000 -     0x7fff649faff3  com.apple.TCC (1.0 - 1) <FD146B21-6DC0-3B66-BB95-57A5016B1365> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff64f1f000 -     0x7fff64fe5ff0  com.apple.TextureIO (3.10.9 - 3.10.9) <E23E05ED-8190-3564-985E-446F15CB0709> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff65171000 -     0x7fff65172fff  com.apple.TrustEvaluationAgent (2.0 - 33) <11DF5A28-4410-36A8-B3B8-BF1094BE1544> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff651aa000 -     0x7fff65402ff0  com.apple.UIFoundation (1.0 - 662) <DFD3DD4A-E661-3A12-BB02-06898949617D> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff65499000 -     0x7fff6549fffe  com.apple.URLFormatting (119 - 119.18) <CE5B7B2B-7CB9-3214-BFA2-D6D4F13D7652> /System/Library/PrivateFrameworks/URLFormatting.framework/Versions/A/URLFormatting
    0x7fff66075000 -     0x7fff66095ffc  com.apple.UserManagement (1.0 - 1) <E168206A-9DC1-3C67-A9A6-52D816DBD5B1> /System/Library/PrivateFrameworks/UserManagement.framework/Versions/A/UserManagement
    0x7fff66e41000 -     0x7fff66f2bff8  com.apple.ViewBridge (464.1 - 464.1) <C698BAC9-26C8-39F1-BBC0-F57EBD2EFD7B> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff670d1000 -     0x7fff670d2fff  com.apple.WatchdogClient.framework (1.0 - 67.120.2) <3B8EBB6B-77D0-317C-A3DB-D0D2E294B18D> /System/Library/PrivateFrameworks/WatchdogClient.framework/Versions/A/WatchdogClient
    0x7fff672a5000 -     0x7fff672a5fff  com.apple.WebInspectorUI (15609 - 15609.2.9.1.2) <7BDB4287-9F2D-399E-9850-F6F9CDAC5D33> /System/Library/PrivateFrameworks/WebInspectorUI.framework/Versions/A/WebInspectorUI
    0x7fff6745e000 -     0x7fff67499fff  libAWDSupport.dylib (949) <C4E783A8-A8D8-307D-AD50-3B66A8944B8E> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib
    0x7fff6749a000 -     0x7fff6777aff7  libAWDSupportFramework.dylib (3541.1) <1F4FB417-EE92-3095-9940-C35C93F6F020> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupportFramework.dylib
    0x7fff6777b000 -     0x7fff6778cfff  libprotobuf-lite.dylib (3541.1) <3EB3CBE0-544B-38D1-81EB-7D73CA221967> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf-lite.dylib
    0x7fff6778d000 -     0x7fff677e6ffb  libprotobuf.dylib (3541.1) <45F77AE5-5D7A-30E7-9168-5546FDC59CA2> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
    0x7fff677e7000 -     0x7fff6782bff6  com.apple.awd (1.0 - 949) <DAF51750-FD03-3509-9CBB-83E9EF0FB363> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/WirelessDiagnostics
    0x7fff67cff000 -     0x7fff67d02ffa  com.apple.dt.XCTTargetBootstrap (1.0 - 16091) <D4F09EC7-C63F-3861-B5DA-3F7C0DFF153D> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff67d7c000 -     0x7fff67d8aff5  com.apple.audio.caulk (1.0 - 32.3) <7D3D2F91-8B1D-3558-B324-45BDF11306DB> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7fff680cc000 -     0x7fff680ceff3  com.apple.loginsupport (1.0 - 1) <31F02734-1ECF-37D9-9DF6-7C3BC3A324FE> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff680cf000 -     0x7fff680e2ffd  com.apple.login (3.0 - 3.0) <1DC570FD-29EC-3AE8-BD34-D44C00E4621B> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff68114000 -     0x7fff68120ffd  com.apple.perfdata (1.0 - 51.100.6) <2F2B9D0F-CB87-3712-B04B-DA075A48002B> /System/Library/PrivateFrameworks/perfdata.framework/Versions/A/perfdata
    0x7fff6aac0000 -     0x7fff6aad5ffe  libAccessibility.dylib (2790.70) <0175DCAB-ADCB-3F8F-BD64-E8E51C00825E> /usr/lib/libAccessibility.dylib
    0x7fff6aba5000 -     0x7fff6abb1ff9  libAudioStatistics.dylib (1104.84) <CBFD7F79-15F1-3828-B2FF-921F71C91FDC> /usr/lib/libAudioStatistics.dylib
    0x7fff6abb2000 -     0x7fff6abe5ffa  libAudioToolboxUtility.dylib (1104.84) <BB234563-F952-3E7F-B630-4140DB5E0380> /usr/lib/libAudioToolboxUtility.dylib
    0x7fff6abec000 -     0x7fff6ac20fff  libCRFSuite.dylib (48) <02C52318-C537-3FD8-BBC4-E5BD25430652> /usr/lib/libCRFSuite.dylib
    0x7fff6ac23000 -     0x7fff6ac2dfff  libChineseTokenizer.dylib (34) <04A7CB5A-FD68-398A-A206-33A510C115E7> /usr/lib/libChineseTokenizer.dylib
    0x7fff6ac2e000 -     0x7fff6acb6fff  libCoreStorage.dylib (551) <BBD3B3DC-270D-35F2-8C67-4595A257EEBB> /usr/lib/libCoreStorage.dylib
    0x7fff6acb9000 -     0x7fff6acbbff7  libDiagnosticMessagesClient.dylib (112) <27220E98-6CE2-33E3-BD48-3CC3CE4AA036> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6ad01000 -     0x7fff6aeb8ffb  libFosl_dynamic.dylib (100.4) <68038226-8CAA-36B5-B5D6-510F900B318D> /usr/lib/libFosl_dynamic.dylib
    0x7fff6aedf000 -     0x7fff6aee5ff3  libIOReport.dylib (54) <E3A2148E-C5B2-30A8-ACD3-E081DD02BE90> /usr/lib/libIOReport.dylib
    0x7fff6afc7000 -     0x7fff6afcefff  libMatch.1.dylib (36) <081FB6A9-0482-3697-A98B-6821FF476C6E> /usr/lib/libMatch.1.dylib
    0x7fff6affd000 -     0x7fff6b01dfff  libMobileGestalt.dylib (826.120.5) <1977AD00-533A-31AA-8D74-EA6CB962F668> /usr/lib/libMobileGestalt.dylib
    0x7fff6b09d000 -     0x7fff6b17aff7  libSMC.dylib (20) <5FCE668E-C4D5-3E36-98B9-6DF720DCD886> /usr/lib/libSMC.dylib
    0x7fff6b18f000 -     0x7fff6b190fff  libSystem.B.dylib (1281.100.1) <B6FDA8A9-3D2B-3BD5-B5B0-57D311C0FF3D> /usr/lib/libSystem.B.dylib
    0x7fff6b191000 -     0x7fff6b21cff7  libTelephonyUtilDynamic.dylib (5017.1) <4C11A09D-9B7E-3743-B9E6-39B4D466BAF1> /usr/lib/libTelephonyUtilDynamic.dylib
    0x7fff6b21d000 -     0x7fff6b21efff  libThaiTokenizer.dylib (3) <97DC10ED-3C11-3C89-B366-299A644035E7> /usr/lib/libThaiTokenizer.dylib
    0x7fff6b236000 -     0x7fff6b24cfff  libapple_nghttp2.dylib (1.39.2) <B99D7150-D4E2-31A2-A594-36DA4B90D558> /usr/lib/libapple_nghttp2.dylib
    0x7fff6b281000 -     0x7fff6b2f3ff7  libarchive.2.dylib (72.100.1) <20B70252-0C4B-3AFD-8C8D-F51921E9D324> /usr/lib/libarchive.2.dylib
    0x7fff6b2f4000 -     0x7fff6b38dfe5  libate.dylib (3.0.1) <C4A5AE88-4E44-36FA-AD3E-0629AF9B94E0> /usr/lib/libate.dylib
    0x7fff6b391000 -     0x7fff6b391ff3  libauto.dylib (187) <85383E24-1592-36BC-BB39-308B7F1C826E> /usr/lib/libauto.dylib
    0x7fff6b457000 -     0x7fff6b467ffb  libbsm.0.dylib (60.100.1) <B2331E11-3CBB-3BCF-93A6-12627AE444D0> /usr/lib/libbsm.0.dylib
    0x7fff6b468000 -     0x7fff6b474fff  libbz2.1.0.dylib (44) <BF40E193-8856-39B7-98F8-7A17B328B1E9> /usr/lib/libbz2.1.0.dylib
    0x7fff6b475000 -     0x7fff6b4c7fff  libc++.1.dylib (902.1) <AD0805FE-F98B-3E2F-B072-83782B22DAC9> /usr/lib/libc++.1.dylib
    0x7fff6b4c8000 -     0x7fff6b4ddffb  libc++abi.dylib (902) <771E9263-E832-3985-9477-8F1B2D73B771> /usr/lib/libc++abi.dylib
    0x7fff6b4de000 -     0x7fff6b4defff  libcharset.1.dylib (59) <FF23D4ED-A5AD-3592-9574-48486C7DF85B> /usr/lib/libcharset.1.dylib
    0x7fff6b4df000 -     0x7fff6b4f0fff  libcmph.dylib (8) <296A51E6-9661-3AC2-A1C9-F1E3510F91AA> /usr/lib/libcmph.dylib
    0x7fff6b4f1000 -     0x7fff6b508fd7  libcompression.dylib (87) <21F37C2E-B9AA-38CE-9023-B763C8828AC6> /usr/lib/libcompression.dylib
    0x7fff6b7e2000 -     0x7fff6b7f8ff7  libcoretls.dylib (167) <9E5D1E0C-03F8-37B6-82A1-0D0597021CB8> /usr/lib/libcoretls.dylib
    0x7fff6b7f9000 -     0x7fff6b7fafff  libcoretls_cfhelpers.dylib (167) <C23BE09B-85D1-3744-9E7B-E2B11ACD5442> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff6bc9d000 -     0x7fff6bda1fef  libcrypto.44.dylib (47.120.1) <B48C0D1A-CDCB-34E4-921E-00EBFF1208DE> /usr/lib/libcrypto.44.dylib
    0x7fff6bda4000 -     0x7fff6bdaffff  libcsfde.dylib (551) <8FBB94EC-712C-3C0F-A8A9-88EE5F4679EF> /usr/lib/libcsfde.dylib
    0x7fff6bdb7000 -     0x7fff6be16ff7  libcups.2.dylib (483.6) <FFE8FE67-A6CC-3C38-A9D7-D411D7B562F1> /usr/lib/libcups.2.dylib
    0x7fff6be18000 -     0x7fff6be7dff7  libcurl.4.dylib (118.120.2) <F2C246F3-460E-31A7-B900-2A9560533730> /usr/lib/libcurl.4.dylib
    0x7fff6bf20000 -     0x7fff6bf20fff  libenergytrace.dylib (21) <DBF8BDEE-7229-3F06-AC10-A28DCC4243C0> /usr/lib/libenergytrace.dylib
    0x7fff6bf21000 -     0x7fff6bf39fff  libexpat.1.dylib (19.60.2) <C9163264-BA81-3CC6-9B8C-48A9A0709DD5> /usr/lib/libexpat.1.dylib
    0x7fff6bf47000 -     0x7fff6bf49fff  libfakelink.dylib (149.1) <122F530F-F10E-3DD5-BBEA-91796BE583F3> /usr/lib/libfakelink.dylib
    0x7fff6bf58000 -     0x7fff6bf5dfff  libgermantok.dylib (24) <DD279BF6-E906-30D3-A69E-DC797E95F147> /usr/lib/libgermantok.dylib
    0x7fff6bf5e000 -     0x7fff6bf67ff7  libheimdal-asn1.dylib (564.100.1) <68FA1BE5-8FFC-3345-8980-8D8629EBA451> /usr/lib/libheimdal-asn1.dylib
    0x7fff6bf68000 -     0x7fff6c058fff  libiconv.2.dylib (59) <F58FED71-6CCA-30E8-9A51-13E9B46E568D> /usr/lib/libiconv.2.dylib
    0x7fff6c059000 -     0x7fff6c2b0fff  libicucore.A.dylib (64260.0.1) <7B9204AC-EA14-3FF3-B6B9-4C85B37EED79> /usr/lib/libicucore.A.dylib
    0x7fff6c2ca000 -     0x7fff6c2cbfff  liblangid.dylib (133) <36581D30-1C7B-3A58-AA07-36237BD75E0E> /usr/lib/liblangid.dylib
    0x7fff6c2cc000 -     0x7fff6c2e4ff3  liblzma.5.dylib (16) <4DB30730-DBD1-3503-957A-D604049B98F9> /usr/lib/liblzma.5.dylib
    0x7fff6c2fc000 -     0x7fff6c3a3ff7  libmecab.dylib (883.11) <66AD729B-2BCC-3347-B9B3-FD88570E884D> /usr/lib/libmecab.dylib
    0x7fff6c3a4000 -     0x7fff6c606ff1  libmecabra.dylib (883.11) <2AE744D2-AC95-3720-8E66-4F9C7A79384C> /usr/lib/libmecabra.dylib
    0x7fff6c973000 -     0x7fff6c9a2fff  libncurses.5.4.dylib (57) <B0B09D08-A7C9-38E9-8BF4-E4F4882F93A6> /usr/lib/libncurses.5.4.dylib
    0x7fff6cad2000 -     0x7fff6cf4eff5  libnetwork.dylib (1880.120.4) <715FB943-BA01-351C-BEA6-121970472985> /usr/lib/libnetwork.dylib
    0x7fff6cf4f000 -     0x7fff6cf66fff  libnetworkextension.dylib (1095.120.6) <782E43F6-1FB9-3A5F-AF24-AC21A63C1A37> /usr/lib/libnetworkextension.dylib
    0x7fff6cfef000 -     0x7fff6d022fde  libobjc.A.dylib (787.1) <CA836D3E-4595-33F1-B70C-7E39A3FBBE16> /usr/lib/libobjc.A.dylib
    0x7fff6d023000 -     0x7fff6d024ff7  libodfde.dylib (26) <2DDA61BF-E92A-3463-B1C4-D59E40D34D34> /usr/lib/libodfde.dylib
    0x7fff6d035000 -     0x7fff6d039fff  libpam.2.dylib (25.100.1) <732E8D8E-C630-3EC2-B6C3-A1564E3B68B8> /usr/lib/libpam.2.dylib
    0x7fff6d03c000 -     0x7fff6d072ff7  libpcap.A.dylib (89.120.1) <CF2ADF15-2D44-3A35-94B4-DD24052F9B23> /usr/lib/libpcap.A.dylib
    0x7fff6d0b2000 -     0x7fff6d0c0ff9  libperfcheck.dylib (37.100.2) <4B1B7D59-2A8B-3E32-AAE6-B428252A5204> /usr/lib/libperfcheck.dylib
    0x7fff6d0f6000 -     0x7fff6d10efff  libresolv.9.dylib (67.40.1) <B0F5D204-7EF2-3B0B-90EF-BB4D196FCC62> /usr/lib/libresolv.9.dylib
    0x7fff6d110000 -     0x7fff6d154ff7  libsandbox.1.dylib (1217.120.7) <728BC15F-9A6C-3634-9427-60C01CB5A5D6> /usr/lib/libsandbox.1.dylib
    0x7fff6d155000 -     0x7fff6d167ff7  libsasl2.2.dylib (213.120.1) <E6375405-168D-3B75-8042-C8B329D01AB9> /usr/lib/libsasl2.2.dylib
    0x7fff6d168000 -     0x7fff6d169ff7  libspindump.dylib (281.3) <0C3A8B48-DC31-3F61-B4CC-746157042D0E> /usr/lib/libspindump.dylib
    0x7fff6d16a000 -     0x7fff6d354ff7  libsqlite3.dylib (308.5) <AF518115-4AD1-39F2-9B82-E2640E2221E1> /usr/lib/libsqlite3.dylib
    0x7fff6d448000 -     0x7fff6d475ffb  libssl.46.dylib (47.120.1) <6209494A-4AAD-344E-992C-03ACD2D4C402> /usr/lib/libssl.46.dylib
    0x7fff6d5a5000 -     0x7fff6d5a8ffb  libutil.dylib (57) <D33B63D2-ADC2-38BD-B8F2-24056C41E07B> /usr/lib/libutil.dylib
    0x7fff6d5a9000 -     0x7fff6d5b6ff7  libxar.1.dylib (425.2) <943A4CBB-331B-3A04-A11F-A2301189D40B> /usr/lib/libxar.1.dylib
    0x7fff6d5bc000 -     0x7fff6d69eff7  libxml2.2.dylib (33.3) <262EF7C6-7D83-3C01-863F-36E97F5ACD34> /usr/lib/libxml2.2.dylib
    0x7fff6d6a2000 -     0x7fff6d6cafff  libxslt.1.dylib (16.9) <86FE4382-BD77-3C19-A678-11EBCD70685A> /usr/lib/libxslt.1.dylib
    0x7fff6d6cb000 -     0x7fff6d6ddff3  libz.1.dylib (76) <DB120508-3BED-37A8-B439-5235EAB4618A> /usr/lib/libz.1.dylib
    0x7fff6df8b000 -     0x7fff6df90ff3  libcache.dylib (83) <A5ECC751-A681-30D8-B33C-D192C15D25C8> /usr/lib/system/libcache.dylib
    0x7fff6df91000 -     0x7fff6df9cfff  libcommonCrypto.dylib (60165.120.1) <C321A74A-AA91-3785-BEBF-BEDC6975026C> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6df9d000 -     0x7fff6dfa4fff  libcompiler_rt.dylib (101.2) <652A6012-7E5C-3F4F-9438-86BC094526F3> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6dfa5000 -     0x7fff6dfaeff7  libcopyfile.dylib (166.40.1) <40113A69-A81C-3397-ADC6-1D16B9A22C3E> /usr/lib/system/libcopyfile.dylib
    0x7fff6dfaf000 -     0x7fff6e041fe3  libcorecrypto.dylib (866.120.3) <5E4B0E50-24DD-3E04-9374-EDA9FFD6257B> /usr/lib/system/libcorecrypto.dylib
    0x7fff6e14e000 -     0x7fff6e18eff0  libdispatch.dylib (1173.100.2) <201EDBF3-0B36-31BA-A7CB-443CE35C05D4> /usr/lib/system/libdispatch.dylib
    0x7fff6e18f000 -     0x7fff6e1c5fff  libdyld.dylib (750.5) <7E711A46-5E4D-393C-AEA6-440E2A5CCD0C> /usr/lib/system/libdyld.dylib
    0x7fff6e1c6000 -     0x7fff6e1c6ffb  libkeymgr.dylib (30) <52662CAA-DB1F-30A3-BE13-D6274B1A6D7B> /usr/lib/system/libkeymgr.dylib
    0x7fff6e1c7000 -     0x7fff6e1d3ff3  libkxld.dylib (6153.121.2) <5EBB4886-C7B6-31D6-AA63-D861B2D58FCE> /usr/lib/system/libkxld.dylib
    0x7fff6e1d4000 -     0x7fff6e1d4ff7  liblaunch.dylib (1738.120.8) <07CF647B-F9DC-3907-AD98-2F85FCB34A72> /usr/lib/system/liblaunch.dylib
    0x7fff6e1d5000 -     0x7fff6e1daff7  libmacho.dylib (959.0.1) <D91DFF00-E22F-3796-8A1C-4C1F5F8FA03C> /usr/lib/system/libmacho.dylib
    0x7fff6e1db000 -     0x7fff6e1ddff3  libquarantine.dylib (110.40.3) <D3B7D02C-7646-3FB4-8529-B36DCC2419EA> /usr/lib/system/libquarantine.dylib
    0x7fff6e1de000 -     0x7fff6e1dfff7  libremovefile.dylib (48) <B5E88D9B-C2BE-3496-BBB2-C996317E18A3> /usr/lib/system/libremovefile.dylib
    0x7fff6e1e0000 -     0x7fff6e1f7ff3  libsystem_asl.dylib (377.60.2) <1170348D-2491-33F1-AA79-E2A05B4A287C> /usr/lib/system/libsystem_asl.dylib
    0x7fff6e1f8000 -     0x7fff6e1f8ff7  libsystem_blocks.dylib (74) <7AFBCAA6-81BE-36C3-8DB0-AAE0A4ACE4C5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6e1f9000 -     0x7fff6e280fff  libsystem_c.dylib (1353.100.2) <935DDCE9-4ED0-3F79-A05A-A123DDE399CC> /usr/lib/system/libsystem_c.dylib
    0x7fff6e281000 -     0x7fff6e284ffb  libsystem_configuration.dylib (1061.120.2) <EA9BC2B1-5001-3463-9FAF-39FF61CAC87C> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6e285000 -     0x7fff6e288fff  libsystem_coreservices.dylib (114) <3D0A3AA8-8415-37B2-AAE3-66C03BCE8B55> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6e289000 -     0x7fff6e291fff  libsystem_darwin.dylib (1353.100.2) <6EEC9975-EE3B-3C95-AA5B-030FD10587BC> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6e292000 -     0x7fff6e299fff  libsystem_dnssd.dylib (1096.100.3) <0115092A-E61B-317D-8670-41C7C34B1A82> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6e29a000 -     0x7fff6e29bffb  libsystem_featureflags.dylib (17) <AFDB5095-0472-34AC-BA7E-497921BF030A> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff6e29c000 -     0x7fff6e2e9ff7  libsystem_info.dylib (538) <851693E9-C079-3547-AD41-353F8C248BE8> /usr/lib/system/libsystem_info.dylib
    0x7fff6e2ea000 -     0x7fff6e316ff7  libsystem_kernel.dylib (6153.121.2) <9F9902C9-A46F-3CA9-B7F9-5CCFE98FBF75> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6e317000 -     0x7fff6e35efff  libsystem_m.dylib (3178) <436CFF76-6A99-36F2-A3B6-8D017396A050> /usr/lib/system/libsystem_m.dylib
    0x7fff6e35f000 -     0x7fff6e386fff  libsystem_malloc.dylib (283.100.6) <D4BA7DF2-57AC-33B0-B948-A688EE43C799> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6e387000 -     0x7fff6e394ffb  libsystem_networkextension.dylib (1095.120.6) <6DE86DB0-8CD2-361E-BD6A-A34282B47847> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6e395000 -     0x7fff6e39eff7  libsystem_notify.dylib (241.100.2) <7E9E2FC8-DF26-340C-B196-B81B11850C46> /usr/lib/system/libsystem_notify.dylib
    0x7fff6e39f000 -     0x7fff6e3a7fef  libsystem_platform.dylib (220.100.1) <736920EA-6AE0-3B1B-BBDA-7DCDF0C229DF> /usr/lib/system/libsystem_platform.dylib
    0x7fff6e3a8000 -     0x7fff6e3b2fff  libsystem_pthread.dylib (416.100.3) <77488669-19A3-3993-AD65-CA5377E2475A> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6e3b3000 -     0x7fff6e3b7ff3  libsystem_sandbox.dylib (1217.120.7) <20C93D69-6452-3C82-9521-8AE54345C66F> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6e3b8000 -     0x7fff6e3bafff  libsystem_secinit.dylib (62.100.2) <E851113D-D5B1-3FB0-9D29-9C7647A71961> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6e3bb000 -     0x7fff6e3c2ffb  libsystem_symptoms.dylib (1238.120.1) <25C3866B-004E-3621-9CD3-B1E9C4D887EB> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6e3c3000 -     0x7fff6e3d9ff2  libsystem_trace.dylib (1147.120) <A1ED1D3A-5FAD-3559-A1D6-1BE4E1C5756A> /usr/lib/system/libsystem_trace.dylib
    0x7fff6e3db000 -     0x7fff6e3e0ff7  libunwind.dylib (35.4) <253A12E2-F88F-3838-A666-C5306F833CB8> /usr/lib/system/libunwind.dylib
    0x7fff6e3e1000 -     0x7fff6e416ffe  libxpc.dylib (1738.120.8) <68D433B6-DCFF-385D-8620-F847FB7D4A5A> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 6082635
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=723.6M resident=0K(0%) swapped_out_or_unallocated=723.6M(100%)
Writable regions: Total=692.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=692.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              1664K       13 
Activity Tracing                   256K        1 
CG backing stores                 1480K        4 
CG image                           236K       32 
CoreAnimation                     7172K      169 
CoreGraphics                         8K        1 
CoreImage                           96K       20 
CoreUI image data                 2348K       32 
Foundation                          24K        2 
Image IO                            60K       14 
JS VM Isolated Heap                 24K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           276.0M       91 
MALLOC guard page                   48K       11 
MALLOC_LARGE (reserved)           1024K        1         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Memory Tag 242                      12K        1 
Memory Tag 251                      12K        1 
SQLite page cache                   64K        1 
STACK GUARD                       56.0M       12 
Stack                             13.6M       12 
VM_ALLOCATE                        152K       24 
WebKit Malloc                     7272K       10 
__DATA                            43.3M      398 
__DATA_CONST                        41K        3 
__FONT_DATA                          4K        1 
__LINKEDIT                       388.9M       10 
__OBJC_RO                         32.2M        1 
__OBJC_RW                         1892K        2 
__TEXT                           334.7M      387 
__UNICODE                          564K        1 
mapped file                       90.9M       71 
shared memory                      648K       17 
===========                     =======  ======= 
TOTAL                              1.6G     1346 
TOTAL, minus reserved VM space     1.2G     1346 

Model: MacBookPro16,1, BootROM 1037.120.87.0.0 (iBridge: 17.16.15300.0.0,0), 6 processors, 6-Core Intel Core i7, 2.6 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5300MItem, AMD Radeon Pro 5300M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Apr  7 2020 13:09:12 version 9.30.357.41.32.5.49 FWID 01-617711e7
Bluetooth: Version 7.0.5f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.0 Hub
USB Device: Mass Storage Device
USB Device: USB 10/100/1000 LAN
USB Device: USB 3.1 Bus
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB 2.0 BILLBOARD
USB Device: USB Billboard Device
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3</details>

I received the following error in the MySQL error logs:

```
2020-06-22T14:26:52.885822Z 638 [Note] Aborted connection 638 to db: 'test' user: 'root' host: 'localhost' (Got an error reading communication packets)
```

### LINKED ISSUE #72: Crash after SQL import
I need to import 3 databases today, from mysql dumps. Each time, when the import was finished, the app went away, and I got the bug report dialog. One time, it showed me an import finished notification, but the other two times id didn't In each of the cases, I got the Apple crash report dialog, and clicked OK. Hope you got those reports.

It does appear that everything was imported correctly.  FWIW, I've used this feature in Sequel Pro quite often.

### PR DESCRIPTION
**Pull request by gboudreau**
What does this implement/fix? Explain your changes.
---------------------------------------------------
A object was released, and shouldn't have been, causing this crash. Was added in https://github.com/Sequel-Ace/Sequel-Ace/commit/cd9dc082ea7bb1a2edfd2bfd971e555d7568cda9#diff-6bb5f827527ddd9efe02effabf68ff10R174
I also removed duplicated code that caused a warning when running in Xcode.

Does this close any currently open issues?
------------------------------------------
#55
#72

### CODE REVIEW

File: Source/SPFileManagerAdditions.m [hunk 1]
```diff
@@ -171,7 +171,6 @@ - (NSStringEncoding)detectEncodingforFileAtPath:(NSString *)aPath
 	}
 	
 	NSData *startData = [detectorFileHandle readDataOfLength:500];
-	[detectorFileHandle release];
```
Comment (Jason-Morcos) [inline Source/SPFileManagerAdditions.m:174]: Ahhh I think this was probably me. Had to rewrite the file handler to remove a deprecated and unsupported encoding-detection framework. Good catch!

File: Source/SPDataImport.m [hunk 2]
```diff
@@ -889,18 +889,6 @@ - (void)importCSVFile:(NSString *)filename
...
-	[csvParser setLineTerminatorString:[importLinesTerminatedField stringValue] convertDisplayStrings:YES];
-	[csvParser setFieldQuoteString:[importFieldsEnclosedField stringValue] convertDisplayStrings:YES];
-	if ([[importFieldsEscapedField stringValue] isEqualToString:@"\\ or \""]) {
-		[csvParser setEscapeString:@"\\" convertDisplayStrings:NO];
-	} else {
-		[csvParser setEscapeString:[importFieldsEscapedField stringValue] convertDisplayStrings:YES];
-		[csvParser setEscapeStringsAreMatchedStrictly:YES];
-	}
-	[csvParser setNullReplacementString:[prefs objectForKey:SPNullValue]];
-
```
Comment (Jason-Morcos) [inline Source/SPDataImport.m:903]: Funky! I don't _think_ we changed this from Sequel Pro. Good catch.
