### PR TITLE
#fixed changing custom query font and respect font when inserting favourite

### LINKED ISSUE #487: Cannot change QUERY EDITOR font / font size on Big Sur
- Sequel Ace Version: 2.3.0 Build 2111 (via app store)
- macOS Version: 11.0.1 Big Sur

**Steps To Reproduce**
1. Go to Sequel Ace > Preferences, Click Query Editor
2. Click Select to open the font dialog
3. Change font and font size, observe change not persisted in Font textbox on Sequel Ace and no changes to font in main query editor window

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Present in latest release, 2.3.0, 11th Nov 2020 - https://github.com/Sequel-Ace/Sequel-Ace/tree/2.3.0

**Additional Context**
Have also tested in Sequel Pro to make sure my expectations on when the font should change (or how to correctly use the dialog) are correct. In Sequel Pro when changing the font in the font dialog the textbox labelled Font in preferences immediately changes, as does the font from the main query editor window.

**Screenshot of the issue in Sequel Ace:**
Screenshot 2020-11-13 at 13 21 55

### LINKED ISSUE #753: Query editor fonts not respecting Preferences if restoring a query favourite
- Sequel Ace Version (including build number): 3.0.2 Build 3010
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.22
- macOS Localization: Eng

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The query editor fonts are not respecting the preferences font when restoring a query favorite

**Steps To Reproduce**
1. In the Query tab, click Query Favorite and add a saved query. In the editor the font of the query will be different from your saved font from the Preferences.
2. Type anywhere within the query that was restored, you will then see the Preferences font applied

**Expected Behaviour**

It should look just as the preferences Query Editor font is set to

**Related Issues**

May be related to https://github.com/Sequel-Ace/Sequel-Ace/issues/487

**Additional Context**

You can see in the screenshot below how it behaves. I typed some different numbers in the date range to show how the font styles mix.
image

### PR DESCRIPTION
**Pull request by jamesstout**
## Changes:
- fixed changing custom query font
- fixed respecting font when inserting favourite

## Closes following issues:
- Closes #487 
- Closes #753  

## Tested:
- Processors:
  - [x] Intel
  - [ ] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [x] 10.15.x (Catalina)
  - [x] 11.x (Big Sur)
- Xcode Version: 12.3 (12C33)
- Localizations:
  - [ ] English
  - [ ] Spanish
  - [ ] Other (please specify)

### CODE REVIEW

File: Source/Views/TextViews/SPTextView.m [hunk 1]
```diff
@@ -1910,7 +1910,19 @@ - (void)insertAsSnippet:(NSString*)theSnippet atRange:(NSRange)targetRange
 
 		// Registering for undo
 		[self breakUndoCoalescing];
-		[self.textStorage appendAttributedString:[[NSAttributedString alloc] initWithString:snip]];
+
+        NSMutableAttributedString *tmpAttStr = [[NSMutableAttributedString alloc] initWithString:snip];
+
+        // if we are inserting a favourite query,
+        // add the font
+        // FIXME: should this apply to all snippet inserts actually?
```
Comment (Kaspik) [inline Source/Views/TextViews/SPTextView.m:1918]: Not sure

**Review by Kaspik — APPROVED** [review]

File: Source/Views/TextViews/SPTextView.m (hunk 1 above)
Comment (Jason-Morcos) [reply Source/Views/TextViews/SPTextView.m:1918]: I think this should apply to all snipped inserts, yes?
